table BFPeople
	lineageTag: 27596034-32ac-41cb-9f2c-f5acbe55091e

	column 'Upshot ID'
		dataType: string
		lineageTag: e8b41990-b624-4193-8f53-80de706e0196
		summarizeBy: none
		sourceColumn: Upshot ID

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 14e4b19b-0757-48af-ab2a-8c5a7d6668c4
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Archived on'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 86eddbf4-ffb4-4c7d-b44d-730d1542ef95
		summarizeBy: none
		sourceColumn: Archived on

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'First Name'
		dataType: string
		lineageTag: af7cdb8a-1978-48e3-bd40-e99653502d91
		summarizeBy: none
		sourceColumn: First Name

		annotation SummarizationSetBy = Automatic

	column 'Last Name'
		dataType: string
		lineageTag: 7e70eb10-7a4e-490b-8ecc-925e3dfe403d
		summarizeBy: none
		sourceColumn: Last Name

		annotation SummarizationSetBy = Automatic

	column Nickname
		dataType: string
		lineageTag: cdaa9555-d9c9-4427-b8e6-5e17b44f6308
		summarizeBy: none
		sourceColumn: Nickname

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 8c4789d8-e40a-4a1a-aebf-0be0880152c0
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column 'Date of Birth'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7f5264c0-e42e-44ae-a602-ed6fbb162ccf
		summarizeBy: none
		sourceColumn: Date of Birth

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Age
		dataType: int64
		formatString: 0
		lineageTag: fb182966-bd44-4ead-88c0-835eb908ac8e
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column 'Identifying notes'
		dataType: string
		lineageTag: 9471e65e-47d5-4980-a78d-f6c2f95e3b7b
		summarizeBy: none
		sourceColumn: Identifying notes

		annotation SummarizationSetBy = Automatic

	column 'Address line 1'
		dataType: string
		lineageTag: 47337543-d7a0-4975-9f4c-0cd2a6a38dea
		summarizeBy: none
		sourceColumn: Address line 1

		annotation SummarizationSetBy = Automatic

	column 'Address line 2'
		dataType: string
		lineageTag: 42c81069-6a2d-409e-90c1-0f5729027d5f
		summarizeBy: none
		sourceColumn: Address line 2

		annotation SummarizationSetBy = Automatic

	column 'Address line 3'
		dataType: string
		lineageTag: adb0ac30-fcd6-4e6f-b4e8-410d96fcdddf
		summarizeBy: none
		sourceColumn: Address line 3

		annotation SummarizationSetBy = Automatic

	column Town/City
		dataType: string
		lineageTag: 41f3ba7a-ee3c-4e64-bcdb-6e7eaa05e41c
		summarizeBy: none
		sourceColumn: Town/City

		annotation SummarizationSetBy = Automatic

	column County
		dataType: string
		lineageTag: 44c1613d-27a7-4a26-a8d0-b544134de704
		summarizeBy: none
		sourceColumn: County

		annotation SummarizationSetBy = Automatic

	column Postcode
		dataType: string
		lineageTag: a603a97e-3dbd-44d9-821c-98dffc9bc1ae
		summarizeBy: none
		sourceColumn: Postcode

		annotation SummarizationSetBy = Automatic

	column Longitude
		dataType: double
		lineageTag: cda43e44-85cc-4660-98b5-bb5749362538
		summarizeBy: sum
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Latitude
		dataType: double
		lineageTag: 7389a5e4-ee20-4484-9f15-e16218ad611a
		summarizeBy: sum
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Strategic Authority'
		dataType: string
		lineageTag: 468c9921-c8a5-43de-820b-f899d5abf3bc
		summarizeBy: none
		sourceColumn: Strategic Authority

		annotation SummarizationSetBy = Automatic

	column 'County or Unitary Authority'
		dataType: string
		lineageTag: 6fb1f11a-0ec2-4f61-875d-967f64dde058
		summarizeBy: none
		sourceColumn: County or Unitary Authority

		annotation SummarizationSetBy = Automatic

	column 'Local Authority'
		dataType: string
		lineageTag: d53555d5-5fe0-40e9-aa2e-2c1df6974e91
		summarizeBy: none
		sourceColumn: Local Authority

		annotation SummarizationSetBy = Automatic

	column Constituency
		dataType: string
		lineageTag: e87ef46f-bbe9-4f4c-8720-824af2312e38
		summarizeBy: none
		sourceColumn: Constituency

		annotation SummarizationSetBy = Automatic

	column Ward
		dataType: string
		lineageTag: 4d18aaf7-e537-41c8-b83f-b4492b57e565
		summarizeBy: none
		sourceColumn: Ward

		annotation SummarizationSetBy = Automatic

	column 'LSOA code'
		dataType: string
		lineageTag: e5ed8be3-11fc-490d-b3fc-9f40770ff3ea
		summarizeBy: none
		sourceColumn: LSOA code

		annotation SummarizationSetBy = Automatic

	column 'IMD percent'
		dataType: int64
		formatString: 0
		lineageTag: aa1ffb8b-ef3f-418f-9f4c-ade8e487dc62
		summarizeBy: sum
		sourceColumn: IMD percent

		annotation SummarizationSetBy = Automatic

	column 'Contact relationship type'
		dataType: string
		lineageTag: 0c6fdf1e-9a8a-4b89-a9ce-fb0e3cab66d3
		summarizeBy: none
		sourceColumn: Contact relationship type

		annotation SummarizationSetBy = Automatic

	column 'Contact first name'
		dataType: string
		lineageTag: b34726bc-c9ff-49d8-8ffa-c6a26d161342
		summarizeBy: none
		sourceColumn: Contact first name

		annotation SummarizationSetBy = Automatic

	column 'Contact last name'
		dataType: string
		lineageTag: 04c16a41-3558-46bd-8bc2-498e69634ac7
		summarizeBy: none
		sourceColumn: Contact last name

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 97d822de-11d8-4d35-9af0-92e8e540015f
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column 'Mobile Phone'
		dataType: string
		lineageTag: defbc6d5-de33-4433-b38c-74adadec6a45
		summarizeBy: none
		sourceColumn: Mobile Phone

		annotation SummarizationSetBy = Automatic

	column 'Other telephone'
		dataType: string
		lineageTag: 354cfee7-a31c-4b6b-8e93-6bfb78ade78b
		summarizeBy: none
		sourceColumn: Other telephone

		annotation SummarizationSetBy = Automatic

	column 'Emergency contact details'
		dataType: string
		lineageTag: f283a124-8b80-4e46-9197-4029ed5606a7
		summarizeBy: none
		sourceColumn: Emergency contact details

		annotation SummarizationSetBy = Automatic

	column 'Specific medical conditions'
		dataType: string
		lineageTag: cfd3c5bc-bef3-4eb6-bae8-aa26cca54bde
		summarizeBy: none
		sourceColumn: Specific medical conditions

		annotation SummarizationSetBy = Automatic

	column 'Any other conditions, allergies or dietary requirements etc'
		dataType: string
		lineageTag: 8a3e249a-5a20-49bf-96f0-c35777ca139f
		summarizeBy: none
		sourceColumn: Any other conditions, allergies or dietary requirements etc

		annotation SummarizationSetBy = Automatic

	column Disability
		dataType: string
		lineageTag: 00a552d6-fd97-48c8-88e1-38d7e645a234
		summarizeBy: none
		sourceColumn: Disability

		annotation SummarizationSetBy = Automatic

	column Ethnicity
		dataType: string
		lineageTag: d8d1fe1c-1d27-4ccb-b114-c1c8d94c1739
		summarizeBy: none
		sourceColumn: Ethnicity

		annotation SummarizationSetBy = Automatic

	column Faith
		dataType: string
		lineageTag: 3f8899e5-3605-45fe-96e9-66264e72c9f2
		summarizeBy: none
		sourceColumn: Faith

		annotation SummarizationSetBy = Automatic

	column 'Sexual orientation'
		dataType: string
		lineageTag: a69b3ec8-518c-459c-8449-7560222c7906
		summarizeBy: none
		sourceColumn: Sexual orientation

		annotation SummarizationSetBy = Automatic

	column School/College/University
		dataType: string
		lineageTag: d309924a-77e7-4c1d-8b71-5e34f0dd3b68
		summarizeBy: none
		sourceColumn: School/College/University

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 4e3e8aa4-5c92-4ea3-9093-0ca487973aed
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column 'Edubase URN'
		dataType: int64
		formatString: 0
		lineageTag: 83ef8e14-1736-4b6e-8741-0fe17d60dab0
		summarizeBy: sum
		sourceColumn: Edubase URN

		annotation SummarizationSetBy = Automatic

	column 'FA number'
		dataType: string
		lineageTag: 35d35e3c-d219-40ba-b17a-e59650c601c2
		summarizeBy: none
		sourceColumn: FA number

		annotation SummarizationSetBy = Automatic

	column 'Membership ID/number'
		dataType: string
		lineageTag: e9d5c641-a9a8-48d5-85f6-27bf3033ea69
		summarizeBy: none
		sourceColumn: Membership ID/number

		annotation SummarizationSetBy = Automatic

	column 'Has permission: Media consent'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8f0b2f83-3103-4eda-831e-c447923e8b64
		summarizeBy: none
		sourceColumn: Has permission: Media consent

		annotation SummarizationSetBy = Automatic

	column 'Has permission: Receive surveys via Upshot'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: fbdacb56-a2ba-47f1-a581-30ae84ece4fe
		summarizeBy: none
		sourceColumn: Has permission: Receive surveys via Upshot

		annotation SummarizationSetBy = Automatic

	column 'Has permission: Receive emails via Upshot'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 83104f3a-818c-4153-ad94-2c5131bf5190
		summarizeBy: none
		sourceColumn: Has permission: Receive emails via Upshot

		annotation SummarizationSetBy = Automatic

	column Registered
		dataType: dateTime
		formatString: Long Date
		lineageTag: a16452a4-8649-4e71-8653-426fff79cc9c
		summarizeBy: none
		sourceColumn: Registered

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Added to Upshot'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f2940a7a-3ef8-47a8-a3f7-0be30f733486
		summarizeBy: none
		sourceColumn: Added to Upshot

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Added by'
		dataType: string
		lineageTag: 596282ad-809e-4bf3-8c48-649ef7db9d65
		summarizeBy: none
		sourceColumn: Added by

		annotation SummarizationSetBy = Automatic

	column 'Added via'
		dataType: string
		lineageTag: 98261941-7b4a-4964-bf42-d4aadd321f18
		summarizeBy: none
		sourceColumn: Added via

		annotation SummarizationSetBy = Automatic

	column 'Last updated'
		dataType: dateTime
		formatString: Long Date
		lineageTag: daa5d5b1-c89c-44b2-983e-114d809c64b7
		summarizeBy: none
		sourceColumn: Last updated

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Last updated by'
		dataType: string
		lineageTag: 570d22a7-871a-4992-aa38-95b71c40e307
		summarizeBy: none
		sourceColumn: Last updated by

		annotation SummarizationSetBy = Automatic

	column 'First session in time period'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6a8a9c5e-d49f-441b-940e-f586293f8806
		summarizeBy: none
		sourceColumn: First session in time period

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Last session in time period'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 41a0a63e-fc0e-44ef-ad4b-c7bed9bd8022
		summarizeBy: none
		sourceColumn: Last session in time period

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Type of Profile:'
		dataType: string
		lineageTag: e57698f8-c88a-4473-9ebc-ff0643381369
		summarizeBy: none
		sourceColumn: Type of Profile:

		annotation SummarizationSetBy = Automatic

	column 'NI Number:'
		dataType: string
		lineageTag: b7be082c-ca54-4d96-b2b6-daad5050ac13
		summarizeBy: none
		sourceColumn: NI Number:

		annotation SummarizationSetBy = Automatic

	column 'What is the highest level of education you have completed?'
		dataType: string
		lineageTag: 4897db34-26e2-4332-9fae-4dedd5fc427a
		summarizeBy: none
		sourceColumn: What is the highest level of education you have completed?

		annotation SummarizationSetBy = Automatic

	column 'Do you have any paid work/long term volunteering experience since leaving school?'
		dataType: string
		lineageTag: b67083f6-7dbf-4625-8798-c2c24ecf5ca3
		summarizeBy: none
		sourceColumn: Do you have any paid work/long term volunteering experience since leaving school?

		annotation SummarizationSetBy = Automatic

	column 'Do you have a driving licence?'
		dataType: string
		lineageTag: 532beb93-680e-4064-84d2-74313870a190
		summarizeBy: none
		sourceColumn: Do you have a driving licence?

		annotation SummarizationSetBy = Automatic

	column 'Status at start of program'
		dataType: string
		lineageTag: 7fc2eb85-aa6d-4b52-89d8-87e908ade620
		summarizeBy: none
		sourceColumn: Status at start of program

		annotation SummarizationSetBy = Automatic

	column 'How long have you been unemployed?'
		dataType: string
		lineageTag: 9d4c40fb-a723-4308-9597-10944bda17df
		summarizeBy: none
		sourceColumn: How long have you been unemployed?

		annotation SummarizationSetBy = Automatic

	column Allergies
		dataType: string
		lineageTag: 8cce1325-c914-49a0-9b99-675de6ccb4ca
		summarizeBy: none
		sourceColumn: Allergies

		annotation SummarizationSetBy = Automatic

	column Other
		dataType: string
		lineageTag: 8a1ac3b2-2333-4907-84f7-34ee46f4fa26
		summarizeBy: none
		sourceColumn: Other

		annotation SummarizationSetBy = Automatic

	column 'Do you personally consider yourself to have a disability, regardless of clinical diagnosis?'
		dataType: string
		lineageTag: 453122d1-c0d5-472c-a17b-e9b3441c1526
		summarizeBy: none
		sourceColumn: Do you personally consider yourself to have a disability, regardless of clinical diagnosis?

		annotation SummarizationSetBy = Automatic

	column 'Do you personally consider yourself to be transgender?'
		dataType: string
		lineageTag: d01dbcd9-7cd3-41c3-9f91-a830e80062ff
		summarizeBy: none
		sourceColumn: Do you personally consider yourself to be transgender?

		annotation SummarizationSetBy = Automatic

	column 'Please indicate if you have any of the following neurodivergent conditions (select all that apply):'
		dataType: string
		lineageTag: 7d9054f5-1a26-46c3-81b4-fb41640ad6df
		summarizeBy: none
		sourceColumn: Please indicate if you have any of the following neurodivergent conditions (select all that apply):

		annotation SummarizationSetBy = Automatic

	column 'Do you have access to the following types of healthcare services?'
		dataType: string
		lineageTag: e4dcf8d5-6361-45e6-a646-6739ed86121e
		summarizeBy: none
		sourceColumn: Do you have access to the following types of healthcare services?

		annotation SummarizationSetBy = Automatic

	column 'Are you care experienced?'
		dataType: string
		lineageTag: 8f3a465d-a0f4-4ef5-bdb0-b5824c131f35
		summarizeBy: none
		sourceColumn: Are you care experienced?

		annotation SummarizationSetBy = Automatic

	column 'Where is your PA based?'
		dataType: string
		lineageTag: 38775dd2-14f3-46b4-9ea3-2bbbbfb0d687
		summarizeBy: none
		sourceColumn: Where is your PA based?

		annotation SummarizationSetBy = Automatic

	column Barriers
		dataType: string
		lineageTag: 7a464fac-859c-408b-b9a8-1f30d8848fd9
		summarizeBy: none
		sourceColumn: Barriers

		annotation SummarizationSetBy = Automatic

	column 'If any of the options on ''Barriers to Employment'' said please state, list detail here:'
		dataType: string
		lineageTag: 41acace0-9e4d-4f1d-aa31-7bbff2650d91
		summarizeBy: none
		sourceColumn: If any of the options on 'Barriers to Employment' said please state, list detail here:

		annotation SummarizationSetBy = Automatic

	column Benefits:
		dataType: string
		lineageTag: c98eb764-ed35-4af2-b1b9-da89eb3d84ec
		summarizeBy: none
		sourceColumn: Benefits:

		annotation SummarizationSetBy = Automatic

	column 'Date of Claim for above:'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a9bc7478-a168-454d-8755-21624b955116
		summarizeBy: none
		sourceColumn: Date of Claim for above:

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Other benefits:'
		dataType: string
		lineageTag: 10a24b12-c796-4183-9611-82f0c37014c8
		summarizeBy: none
		sourceColumn: Other benefits:

		annotation SummarizationSetBy = Automatic

	column 'Living Arrangements:'
		dataType: string
		lineageTag: 4651c5f7-bab6-4753-9fa5-025de0918d0a
		summarizeBy: none
		sourceColumn: Living Arrangements:

		annotation SummarizationSetBy = Automatic

	column 'Are you working with any other service?'
		dataType: string
		lineageTag: 410f92b6-4623-483b-9456-7eaf3a2c66a0
		summarizeBy: none
		sourceColumn: Are you working with any other service?

		annotation SummarizationSetBy = Automatic

	column 'If other services worked with, please state:'
		dataType: string
		lineageTag: 497893dc-8cfb-4730-8118-669d03eb820b
		summarizeBy: none
		sourceColumn: If other services worked with, please state:

		annotation SummarizationSetBy = Automatic

	column 'Which Services?'
		dataType: string
		lineageTag: 4993a338-4cb5-41c9-a4e6-18f90584b8d9
		summarizeBy: none
		sourceColumn: Which Services?

		annotation SummarizationSetBy = Automatic

	column 'Job Center referred by?'
		dataType: string
		lineageTag: 222d662a-68a1-43bb-88fe-4346cbf7fa27
		summarizeBy: none
		sourceColumn: Job Center referred by?

		annotation SummarizationSetBy = Automatic

	column Notes:
		dataType: string
		lineageTag: 63884097-e2e8-4738-98ee-3003fd96feaf
		summarizeBy: none
		sourceColumn: Notes:

		annotation SummarizationSetBy = Automatic

	column 'Leaving Care Worker'
		dataType: string
		lineageTag: 0bb3dd1d-38f4-4fda-905d-1c0a139b1f84
		summarizeBy: none
		sourceColumn: Leaving Care Worker

		annotation SummarizationSetBy = Automatic

	column 'Inspira Worker'
		dataType: string
		lineageTag: bcb3b4fa-d0fb-4056-99d2-25a493f22755
		summarizeBy: none
		sourceColumn: Inspira Worker

		annotation SummarizationSetBy = Automatic

	partition BFPeople = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://cyacumbria.sharepoint.com/sites/CYAAllStaff/Shared%20Documents/General/Data%20Team/Staff%20Cards/CYA%20Staff%20Card%20POW%20BI%20V2.xlsx"), null, true),
				    BFPeople_Table = Source{[Item="BFPeople",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(BFPeople_Table,{{"Upshot ID", type text}, {"Status", type text}, {"Archived on", type date}, {"First Name", type text}, {"Last Name", type text}, {"Nickname", type text}, {"Gender", type text}, {"Date of Birth", type date}, {"Age", Int64.Type}, {"Identifying notes", type any}, {"Address line 1", type text}, {"Address line 2", type text}, {"Address line 3", type text}, {"Town/City", type text}, {"County", type text}, {"Postcode", type text}, {"Longitude", type number}, {"Latitude", type number}, {"Strategic Authority", type text}, {"County or Unitary Authority", type text}, {"Local Authority", type text}, {"Constituency", type text}, {"Ward", type text}, {"LSOA code", type text}, {"IMD percent", Int64.Type}, {"Contact relationship type", type text}, {"Contact first name", type text}, {"Contact last name", type text}, {"Email", type text}, {"Mobile Phone", type text}, {"Other telephone", type text}, {"Emergency contact details", type text}, {"Specific medical conditions", type text}, {"Any other conditions, allergies or dietary requirements etc", type text}, {"Disability", type text}, {"Ethnicity", type text}, {"Faith", type text}, {"Sexual orientation", type text}, {"School/College/University", type text}, {"Type", type text}, {"Edubase URN", Int64.Type}, {"FA number", type text}, {"Membership ID/number", type text}, {"Has permission: Media consent", type logical}, {"Has permission: Receive surveys via Upshot", type logical}, {"Has permission: Receive emails via Upshot", type logical}, {"Registered", type date}, {"Added to Upshot", type date}, {"Added by", type text}, {"Added via", type text}, {"Last updated", type date}, {"Last updated by", type text}, {"First session in time period", type date}, {"Last session in time period", type date}, {"Type of Profile:", type text}, {"NI Number:", type text}, {"What is the highest level of education you have completed?", type text}, {"Do you have any paid work/long term volunteering experience since leaving school?", type text}, {"Do you have a driving licence?", type text}, {"Status at start of program", type text}, {"How long have you been unemployed?", type text}, {"Allergies", type text}, {"Other", type text}, {"Do you personally consider yourself to have a disability, regardless of clinical diagnosis?", type text}, {"Do you personally consider yourself to be transgender?", type text}, {"Please indicate if you have any of the following neurodivergent conditions (select all that apply):", type text}, {"Do you have access to the following types of healthcare services?", type text}, {"Are you care experienced?", type text}, {"Where is your PA based?", type text}, {"Barriers", type text}, {"If any of the options on 'Barriers to Employment' said please state, list detail here:", type text}, {"Benefits:", type text}, {"Date of Claim for above:", type date}, {"Other benefits:", type text}, {"Living Arrangements:", type text}, {"Are you working with any other service?", type text}, {"If other services worked with, please state:", type text}, {"Which Services?", type text}, {"Job Center referred by?", type text}, {"Notes:", type text}, {"Leaving Care Worker", type text}, {"Inspira Worker", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

