table 'CYA TLE'
	lineageTag: 91ec0120-7f42-410d-b41f-5c62f0f2c08c

	measure 'TLE Events (Timeline)' =
			
			VAR SelectedPerson = SELECTEDVALUE ( 'New Reg Data'[Attendee ID] )
			VAR SelectedEventType = SELECTEDVALUE ( 'CYA TLE'[Event type] )
			VAR CurrentDate = SELECTEDVALUE ( 'Timeline Dates'[Date] )
			RETURN
			    IF (
			        SelectedPerson = BLANK ()
			            || SelectedEventType = BLANK ()
			            || CurrentDate = BLANK (),
			        BLANK (),
			        CALCULATE (
			            COUNTROWS ( 'CYA TLE' ),
			            ALL ( 'CYA TLE' ),
			            'CYA TLE'[Attendee ID] = SelectedPerson,
			            'CYA TLE'[Event type] = SelectedEventType,
			            'CYA TLE'[Event date] = CurrentDate
			        )
			    )
		formatString: 0
		lineageTag: 417f156f-7876-47a7-b15f-6155a19a58b8

	measure 'TLE Events (Timeline Tooltip)' =
			
			VAR SelectedPerson = SELECTEDVALUE ( 'New Reg Data'[Attendee ID] )
			VAR CurrentDate = SELECTEDVALUE ( 'Timeline Dates'[Date] )
			RETURN
			    IF (
			        SelectedPerson = BLANK ()
			            || CurrentDate = BLANK (),
			        BLANK (),
			        VAR EventDetails =
			            CALCULATETABLE (
			                SUMMARIZE (
			                    'CYA TLE',
			                    'CYA TLE'[Event type],
			                    'CYA TLE'[Event value]
			                ),
			                ALL ( 'CYA TLE' ),
			                'CYA TLE'[Attendee ID] = SelectedPerson,
			                'CYA TLE'[Event date] = CurrentDate
			            )
			        RETURN
			            IF (
			                COUNTROWS ( EventDetails ) = 0,
			                BLANK (),
			                CONCATENATEX (
			                    EventDetails,
			                    'CYA TLE'[Event type]
			                        & IF (
			                            NOT ISBLANK ( 'CYA TLE'[Event value] ),
			                            ": " & 'CYA TLE'[Event value],
			                            ""
			                        ),
			                    UNICHAR ( 10 )
			                )
			            )
			    )
		lineageTag: 863d1f20-2ad9-4745-97e5-8df5d98a8031

	measure 'TLE Timeline Position' =
			VAR SelectedPerson = SELECTEDVALUE ( 'New Reg Data'[Attendee ID] )
			VAR CurrentDate = SELECTEDVALUE ( 'Timeline Dates'[Date] )
			VAR EventCount =
			    IF (
			        NOT ISBLANK ( SelectedPerson ) && NOT ISBLANK ( CurrentDate ),
			        CALCULATE (
			            COUNTROWS ( 'CYA TLE' ),
			            'CYA TLE'[Attendee ID] = SelectedPerson,
			            'CYA TLE'[Event date] = CurrentDate
			        ),
			        0
			    )
			VAR EventType = SELECTEDVALUE ( 'CYA TLE'[Event type] )
			VAR IsMilestone =
			    EventType IN {
			        "Accreditation",
			        "Enrichment Fund Payment",
			        "Entered Education",
			        "Gained Apprenticeship",
			        "Gained Employment - Full Time",
			        "Gained Employment - Kickstart",
			        "Gained Employment - Other",
			        "Gained Employment - Part Time",
			        "Gained Volunteering",
			        "Gained Work Experience / Work Trail / Work Taster",
			        "ME Tool Score",
			        "ME Tool Action Plan",
			        "ME Tool Stage",
			        "Offer of Education, Employment or Training",
			        "Offer of Interview",
			        "Official decision received - DWP Aligned",
			        "Participated in Work Trial",
			        "Received Funding",
			        "Receiving Driving Lessons",
			        "Sustained Employment / Education"
			    }
			RETURN
			    IF ( EventCount > 0, IF ( IsMilestone, 2, 1 ), BLANK () )
		formatString: 0
		lineageTag: 5a7c9e8f-1d2b-4c3e-9f1a-2b8d7c6e5f4a

	measure 'TLE Timeline Size' =
			VAR SelectedPerson = SELECTEDVALUE ( 'New Reg Data'[Attendee ID] )
			VAR CurrentDate = SELECTEDVALUE ( 'Timeline Dates'[Date] )
			VAR EventCount =
			    IF (
			        NOT ISBLANK ( SelectedPerson ) && NOT ISBLANK ( CurrentDate ),
			        CALCULATE (
			            COUNTROWS ( 'CYA TLE' ),
			            'CYA TLE'[Attendee ID] = SelectedPerson,
			            'CYA TLE'[Event date] = CurrentDate
			        ),
			        0
			    )
			VAR EventType = SELECTEDVALUE ( 'CYA TLE'[Event type] )
			VAR IsMilestone =
			    EventType IN {
			        "Accreditation",
			        "Enrichment Fund Payment",
			        "Entered Education",
			        "Gained Apprenticeship",
			        "Gained Employment - Full Time",
			        "Gained Employment - Kickstart",
			        "Gained Employment - Other",
			        "Gained Employment - Part Time",
			        "Gained Volunteering",
			        "Gained Work Experience / Work Trail / Work Taster",
			        "ME Tool Score",
			        "ME Tool Action Plan",
			        "ME Tool Stage",
			        "Offer of Education, Employment or Training",
			        "Offer of Interview",
			        "Official decision received - DWP Aligned",
			        "Participated in Work Trial",
			        "Received Funding",
			        "Receiving Driving Lessons",
			        "Sustained Employment / Education"
			    }
			RETURN
			    IF ( EventCount > 0, IF ( IsMilestone, 50, 10 ), BLANK () )
		formatString: 0
		lineageTag: 8b3d4a5c-6e7f-8a9b-0c1d-2e3f4a5b6c7d

	measure 'TLE Count for Selected Person' =
			VAR SelectedPerson = SELECTEDVALUE ( 'New Reg Data'[Attendee ID] )
			RETURN
			    IF (
			        NOT ISBLANK ( SelectedPerson ),
			        CALCULATE (
			            COUNTROWS ( 'CYA TLE' ),
			            FILTER ( ALL ( 'CYA TLE' ), 'CYA TLE'[Attendee ID] = SelectedPerson )
			        ),
			        BLANK ()
			    )
		formatString: 0
		lineageTag: 9c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f

	measure 'Event End Date' =
			VAR EventDate = SELECTEDVALUE ( 'CYA TLE'[Event date] )
			RETURN
			    IF ( NOT ISBLANK ( EventDate ), EventDate + 1, BLANK () )
		lineageTag: a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d

	measure 'Milestone Count for Selected Person' =
			VAR SelectedPerson = SELECTEDVALUE ( 'New Reg Data'[Attendee ID] )
			RETURN
			    IF (
			        NOT ISBLANK ( SelectedPerson ),
			        CALCULATE (
			            COUNTROWS ( 'CYA TLE' ),
			            'CYA TLE'[Attendee ID] = SelectedPerson,
			            'CYA TLE'[Event type] IN {
			                "Accreditation",
			                "Enrichment Fund Payment",
			                "Entered Education",
			                "Gained Apprenticeship",
			                "Gained Employment - Full Time",
			                "Gained Employment - Kickstart",
			                "Gained Employment - Other",
			                "Gained Employment - Part Time",
			                "Gained Volunteering",
			                "Gained Work Experience / Work Trail / Work Taster",
			                "ME Tool Score",
			                "ME Tool Action Plan",
			                "ME Tool Stage",
			                "Offer of Education, Employment or Training",
			                "Offer of Interview",
			                "Official decision received - DWP Aligned",
			                "Participated in Work Trial",
			                "Received Funding",
			                "Receiving Driving Lessons",
			                "Sustained Employment / Education"
			            }
			        ),
			        BLANK ()
			    )
		formatString: 0
		lineageTag: b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e

	column 'First name'
		dataType: string
		lineageTag: 8b2d49fb-44cd-4100-9af4-f8a1673eddb3
		summarizeBy: none
		sourceColumn: First name

		annotation SummarizationSetBy = Automatic

	column 'Last name'
		dataType: string
		lineageTag: 44b15e54-77e3-43c6-bd99-9ea19e7ef4c2
		summarizeBy: none
		sourceColumn: Last name

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: f2e99144-48ea-48ab-887b-31b7c57848a9
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Event ID'
		dataType: string
		lineageTag: 4f09c7f6-dafe-4d93-8d8d-21d8f24b4723
		summarizeBy: none
		sourceColumn: Event ID

		annotation SummarizationSetBy = Automatic

	column 'Event date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d9019597-c04e-42e1-8700-0a269aa005b5
		summarizeBy: none
		sourceColumn: Event date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Expiry date'
		dataType: string
		lineageTag: 35401371-8bb8-495f-98dd-62f956db8d92
		summarizeBy: none
		sourceColumn: Expiry date

		annotation SummarizationSetBy = Automatic

	column 'Event type'
		dataType: string
		lineageTag: 3a32dcb0-d384-408b-a103-7efd7f318680
		summarizeBy: none
		sourceColumn: Event type

		annotation SummarizationSetBy = Automatic

	column 'Event value'
		dataType: string
		lineageTag: 66c68c9c-0368-49ce-96c5-559cd77946c7
		summarizeBy: none
		sourceColumn: Event value

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"CYA TLE","TableItemName":"Event value (groups)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column Notes
		dataType: string
		lineageTag: ba6b4e60-fca3-4595-b2df-f0a36ef5b6f9
		summarizeBy: none
		sourceColumn: Notes

		annotation SummarizationSetBy = Automatic

	column Project
		dataType: string
		lineageTag: 358ea996-8eff-4317-8e4a-e726f75744cf
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column Activity
		dataType: string
		lineageTag: 87c7d393-5f54-43ff-84ee-918a56138140
		summarizeBy: none
		sourceColumn: Activity

		annotation SummarizationSetBy = Automatic

	column 'Activity Group'
		dataType: string
		lineageTag: 2a5e9231-e0e7-4fd1-af5d-8640beada0f8
		summarizeBy: none
		sourceColumn: Activity Group

		annotation SummarizationSetBy = Automatic

	column 'Activity Type'
		dataType: string
		lineageTag: e64782c5-4d4f-4ba5-9f15-3f3bd4e5f102
		summarizeBy: none
		sourceColumn: Activity Type

		annotation SummarizationSetBy = Automatic

	column 'Recording user first name'
		dataType: string
		lineageTag: ab0ae3b7-cb9d-4163-ab94-fcaec7a1420a
		summarizeBy: none
		sourceColumn: Recording user first name

		annotation SummarizationSetBy = Automatic

	column 'Recording user last name'
		dataType: string
		lineageTag: 2872b09a-4fc2-4167-98e0-70549e1bcf05
		summarizeBy: none
		sourceColumn: Recording user last name

		annotation SummarizationSetBy = Automatic

	column 'Date recorded'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e89a2c7c-d6bd-470f-a63e-93c5920c0aa2
		summarizeBy: none
		sourceColumn: Date recorded

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Time recorded'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 85cefff1-e620-4ee9-b4fe-08c2cb132105
		summarizeBy: none
		sourceColumn: Time recorded

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Event value (groups)' =
			SWITCH(
				TRUE,
				ISBLANK('CYA TLE'[Event value]),
				"(Blank)",
				'CYA TLE'[Event value] IN {"Actively engaging"},
				"Actively engaging",
				"Other"
			)
		lineageTag: 41eb40e5-006e-468f-9d9f-1763ce08955d
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "CYA TLE"
				          }
				        },
				        "Property": "Event value"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"c","Entity":"CYA TLE"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"c"}},"Property":"Event value"}}],"GroupItems":[{"DisplayName":"(Blank)","BlankDefaultPlaceholder":true},{"DisplayName":"Actively engaging","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"c"}},"Property":"Event value"}}],"Values":[[{"Literal":{"Value":"'Actively engaging'"}}]]}}},{"DisplayName":"Other"}]}

		annotation SummarizationSetBy = Automatic

	column 'Attendee ID'
		dataType: string
		lineageTag: 3af2e25e-142b-4c3d-9c45-e8d762fbbe6a
		summarizeBy: none
		sourceColumn: Attendee ID

		annotation SummarizationSetBy = Automatic

	column 'Event Category' =
			SWITCH (
			    TRUE (),
			    [Event type] IN {
			        "Gained Employment - Full Time",
			        "Gained Employment - Part Time",
			        "Gained Employment - Kickstart",
			        "Gained Employment - Other",
			        "Sustained Employment / Education"
			    }, "Employment",
			    [Event type] IN {
			        "Gained Apprenticeship"
			    }, "Apprenticeship",
			    [Event type] IN {
			        "Entered Education",
			        "Offer of Education, Employment or Training"
			    }, "Education",
			    [Event type] IN {
			        "Gained Volunteering"
			    }, "Volunteering",
			    [Event type] IN {
			        "Gained Work Experience / Work Trail / Work Taster",
			        "Participated in Work Trial"
			    }, "Work Experience",
			    [Event type] IN {
			        "Offer of Interview"
			    }, "Interview",
			    [Event type] IN {
			        "ME Tool Score",
			        "ME Tool Action Plan",
			        "ME Tool Stage"
			    }, "ME Tool",
			    [Event type] IN {
			        "Official decision received - DWP Aligned"
			    }, "DWP Decision",
			    [Event type] IN {
			        "Accreditation"
			    }, "Accreditation",
			    [Event type] IN {
			        "Enrichment Fund Payment",
			        "Received Funding"
			    }, "Funding",
			    [Event type] IN {
			        "Receiving Driving Lessons"
			    }, "Driving Lessons",
			    "Other Events"
			)
		dataType: string
		lineageTag: f1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'CYA TLE' = m
		mode: import
		source =
				let
				    WorkbookUrl = "https://cyacumbria.sharepoint.com/sites/CYAAllStaff/Shared%20Documents/General/Data%20Team/Staff%20Cards/CYA%20Staff%20Card%20POW%20BI%20V2.xlsx",
				    Source = Excel.Workbook(Web.Contents(WorkbookUrl), null, true),
				    TLETypeMap = {
				        {"Attendee ID", type text},
				        {"First name", type text},
				        {"Last name", type text},
				        {"Status", type text},
				        {"Event ID", type text},
				        {"Event date", type date},
				        {"Expiry date", type text},
				        {"Event type", type text},
				        {"Event value", type text},
				        {"Notes", type text},
				        {"Project", type text},
				        {"Activity", type text},
				        {"Activity Group", type text},
				        {"Activity Type", type text},
				        {"Recording user first name", type text},
				        {"Recording user last name", type text},
				        {"Date recorded", type date},
				        {"Time recorded", type time}
				    },
				    GetTLE = (item as text) as table =>
				        let
				            Raw = Source{[Item = item, Kind = "Table"]}[Data],
				            ExistingColumns = List.Select(TLETypeMap, each List.Contains(Table.ColumnNames(Raw), _{0})),
				            Typed = Table.TransformColumnTypes(Raw, ExistingColumns, "en-GB"),
				            MissingColumns = List.Select(TLETypeMap, each not List.Contains(Table.ColumnNames(Typed), _{0})),
				            WithAllColumns =
				                List.Accumulate(
				                    MissingColumns,
				                    Typed,
				                    (state, current) =>
				                        let
				                            columnName = current{0},
				                            columnType = current{1}
				                        in
				                            Table.AddColumn(state, columnName, each null, columnType)
				                )
				        in
				            WithAllColumns,
				    Combined = Table.Combine({
				        GetTLE("DOTLE"),
				        GetTLE("BFTLE"),
				        GetTLE("InfraTLE")
				    }),
				    #"Appended Query" = Table.Combine({Combined, #"TE - Data"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Appended Query",{"Attendee ID", "First name", "Last name", "Status", "Event ID", "Event date", "Expiry date", "Event type", "Event value", "Notes", "Project", "Activity", "Activity Group", "Activity Type", "Recording user first name", "Recording user last name", "Date recorded", "Time recorded"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns", {"Event ID"})
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

