table DOMETool
	lineageTag: b0e0305e-5089-466f-a8df-9bedab523e9b

	column 'Sent ID'
		dataType: string
		lineageTag: 5d0def5d-08c3-4ab8-abfe-92f10a4f7e8f
		summarizeBy: none
		sourceColumn: Sent ID

		annotation SummarizationSetBy = Automatic

	column 'Sent name'
		dataType: string
		lineageTag: d7ec0fc1-507b-4bec-a2a5-14b9f6302a12
		summarizeBy: none
		sourceColumn: Sent name

		annotation SummarizationSetBy = Automatic

	column 'Participant name'
		dataType: string
		lineageTag: 38b2632c-7398-43ee-a051-a6ee901234dd
		summarizeBy: none
		sourceColumn: Participant name

		annotation SummarizationSetBy = Automatic

	column 'Upshot ID'
		dataType: string
		lineageTag: 33aaa942-b099-43b4-9f58-1968c6a7d05c
		summarizeBy: none
		sourceColumn: Upshot ID

		annotation SummarizationSetBy = Automatic

	column Submitted
		dataType: dateTime
		formatString: Long Date
		lineageTag: b5917233-7181-4ace-b2a5-0dfded15175e
		summarizeBy: none
		sourceColumn: Submitted

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Q1. Relationships:'
		dataType: int64
		formatString: 0
		lineageTag: a39ce045-5837-4987-a6f2-f6f99e2679e2
		summarizeBy: sum
		sourceColumn: Q1. Relationships:

		annotation SummarizationSetBy = Automatic

	column 'Q2. Employability:'
		dataType: int64
		formatString: 0
		lineageTag: 45065eee-afdb-4248-87e7-c897ecd8ec49
		summarizeBy: sum
		sourceColumn: Q2. Employability:

		annotation SummarizationSetBy = Automatic

	column 'Q3. Key Skills:'
		dataType: int64
		formatString: 0
		lineageTag: 4aff18b8-34f4-4f7e-a568-3ef104211c36
		summarizeBy: sum
		sourceColumn: Q3. Key Skills:

		annotation SummarizationSetBy = Automatic

	column 'Q4. Aspiration and Motivation:'
		dataType: int64
		formatString: 0
		lineageTag: a967fe9b-1ea4-47d7-9846-197f6bc3908c
		summarizeBy: sum
		sourceColumn: Q4. Aspiration and Motivation:

		annotation SummarizationSetBy = Automatic

	column 'Q5. Social Involvement:'
		dataType: int64
		formatString: 0
		lineageTag: 6fc88ff6-2356-4bde-beda-aed6360df92b
		summarizeBy: sum
		sourceColumn: Q5. Social Involvement:

		annotation SummarizationSetBy = Automatic

	column 'Q6. A Healthy Lifestyle:'
		dataType: int64
		formatString: 0
		lineageTag: dcbf18ee-d68a-44d1-a171-262bd6c2d472
		summarizeBy: sum
		sourceColumn: Q6. A Healthy Lifestyle:

		annotation SummarizationSetBy = Automatic

	column 'Q7. Emotional Wellbeing:'
		dataType: int64
		formatString: 0
		lineageTag: 6fd77fa1-c9f3-4fea-9e7f-49861ebc88f7
		summarizeBy: sum
		sourceColumn: Q7. Emotional Wellbeing:

		annotation SummarizationSetBy = Automatic

	column 'Q8. Home and Stability:'
		dataType: int64
		formatString: 0
		lineageTag: ea6f4ca5-1919-4383-afde-51e0463a41cd
		summarizeBy: sum
		sourceColumn: Q8. Home and Stability:

		annotation SummarizationSetBy = Automatic

	column 'Q9. Communication:'
		dataType: int64
		formatString: 0
		lineageTag: 5d1f947e-e3a2-44e0-b3a4-018ac316ceee
		summarizeBy: sum
		sourceColumn: Q9. Communication:

		annotation SummarizationSetBy = Automatic

	column 'Q10. Identity:'
		dataType: int64
		formatString: 0
		lineageTag: 9750e33f-b58d-43c3-b6ed-c56af27c6898
		summarizeBy: sum
		sourceColumn: Q10. Identity:

		annotation SummarizationSetBy = Automatic

	partition DOMETool = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://cyacumbria.sharepoint.com/sites/CYAAllStaff/Shared%20Documents/General/Data%20Team/Staff%20Cards/CYA%20Staff%20Card%20POW%20BI%20V2.xlsx"), null, true),
				    DOMETool_Table = Source{[Item="DOMETool",Kind="Table"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(DOMETool_Table,{"Sent ID", "Sent name", "Participant name", "Upshot ID", "Submitted", "Q1. Relationships:", "Q2. Employability:", "Q3. Key Skills:", "Q4. Aspiration and Motivation:", "Q5. Social Involvement:", "Q6. A Healthy Lifestyle:", "Q7. Emotional Wellbeing:", "Q8. Home and Stability:", "Q9. Communication:", "Q10. Identity:"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Other Columns",{{"Sent ID", type text}, {"Sent name", type text}, {"Participant name", type text}, {"Upshot ID", type text}, {"Submitted", type date}, {"Q1. Relationships:", Int64.Type}, {"Q2. Employability:", Int64.Type}, {"Q3. Key Skills:", Int64.Type}, {"Q4. Aspiration and Motivation:", Int64.Type}, {"Q5. Social Involvement:", Int64.Type}, {"Q6. A Healthy Lifestyle:", Int64.Type}, {"Q7. Emotional Wellbeing:", Int64.Type}, {"Q8. Home and Stability:", Int64.Type}, {"Q9. Communication:", Int64.Type}, {"Q10. Identity:", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

