table DOPeople
	lineageTag: 69201d44-d63c-43af-9a88-446951f764eb

	column 'Upshot ID'
		dataType: string
		lineageTag: 394799a3-6ebc-4996-a0cc-8804badb725b
		summarizeBy: none
		sourceColumn: Upshot ID

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 5377cee5-e11e-413a-bdc7-a2f24d78f40c
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Archived on'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 71e54415-64ad-4ace-a30f-fe16f4109b21
		summarizeBy: none
		sourceColumn: Archived on

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'First Name'
		dataType: string
		lineageTag: 52175c49-5485-4bcc-8524-4faae334d4f2
		summarizeBy: none
		sourceColumn: First Name

		annotation SummarizationSetBy = Automatic

	column 'Last Name'
		dataType: string
		lineageTag: 21470741-00b1-48bd-b327-fcb3c980a66b
		summarizeBy: none
		sourceColumn: Last Name

		annotation SummarizationSetBy = Automatic

	column Nickname
		dataType: string
		lineageTag: c32e27ac-213e-4c09-94b8-b0bd3bcc72d4
		summarizeBy: none
		sourceColumn: Nickname

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: c72df18d-734b-43ac-a1a6-7441730cad24
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column 'Date of Birth'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c97bd51f-eb60-474a-93a5-0732a10978c6
		summarizeBy: none
		sourceColumn: Date of Birth

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 1345c1d7-2e40-4aa0-a573-81b2955a64b0
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column 'Identifying notes'
		dataType: string
		lineageTag: 9e31e9e0-ea5e-4c2f-9faa-675ac62126b0
		summarizeBy: none
		sourceColumn: Identifying notes

		annotation SummarizationSetBy = Automatic

	column 'Address line 1'
		dataType: string
		lineageTag: a5498d19-bb24-45bd-94c5-634e42c23fa1
		summarizeBy: none
		sourceColumn: Address line 1

		annotation SummarizationSetBy = Automatic

	column 'Address line 2'
		dataType: string
		lineageTag: 4232c8ac-de8b-4ae6-859e-c2cb2ab0880e
		summarizeBy: none
		sourceColumn: Address line 2

		annotation SummarizationSetBy = Automatic

	column 'Address line 3'
		dataType: string
		lineageTag: 553fdb1f-7980-4a35-971e-83f84be3c324
		summarizeBy: none
		sourceColumn: Address line 3

		annotation SummarizationSetBy = Automatic

	column Town/City
		dataType: string
		lineageTag: f9f62b27-a32f-40bf-b65b-259e784169b9
		summarizeBy: none
		sourceColumn: Town/City

		annotation SummarizationSetBy = Automatic

	column County
		dataType: string
		lineageTag: e95b69c1-3482-4a96-a302-6d8e548bc7c2
		summarizeBy: none
		sourceColumn: County

		annotation SummarizationSetBy = Automatic

	column Postcode
		dataType: string
		lineageTag: e570c197-388b-475c-a6d1-710d895bc14a
		summarizeBy: none
		sourceColumn: Postcode

		annotation SummarizationSetBy = Automatic

	column Longitude
		dataType: double
		lineageTag: 5a04c5e5-d00b-45b8-9953-a39f21e56036
		summarizeBy: sum
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Latitude
		dataType: double
		lineageTag: dabf0ea8-bdf4-45ea-8568-10c24cffcc67
		summarizeBy: sum
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Strategic Authority'
		dataType: string
		lineageTag: c056c692-c0a1-4847-9784-198278b07068
		summarizeBy: none
		sourceColumn: Strategic Authority

		annotation SummarizationSetBy = Automatic

	column 'County or Unitary Authority'
		dataType: string
		lineageTag: ef20e1cb-ae43-4518-bcb2-6cc75cf4aedd
		summarizeBy: none
		sourceColumn: County or Unitary Authority

		annotation SummarizationSetBy = Automatic

	column 'Local Authority'
		dataType: string
		lineageTag: 97a7f360-83fb-4a0f-991c-5bf0aad9c894
		summarizeBy: none
		sourceColumn: Local Authority

		annotation SummarizationSetBy = Automatic

	column Constituency
		dataType: string
		lineageTag: 729c047f-64bb-41ea-8f32-1beade9eb06b
		summarizeBy: none
		sourceColumn: Constituency

		annotation SummarizationSetBy = Automatic

	column Ward
		dataType: string
		lineageTag: 21031454-6f4d-4bfb-a3f8-3f62b4f35a5b
		summarizeBy: none
		sourceColumn: Ward

		annotation SummarizationSetBy = Automatic

	column 'LSOA code'
		dataType: string
		lineageTag: 96ee0f00-3647-4d73-b82d-238b820caf59
		summarizeBy: none
		sourceColumn: LSOA code

		annotation SummarizationSetBy = Automatic

	column 'IMD percent'
		dataType: int64
		formatString: 0
		lineageTag: c0d548c4-f305-4cdb-bce1-4e1e122de431
		summarizeBy: sum
		sourceColumn: IMD percent

		annotation SummarizationSetBy = Automatic

	column 'Contact relationship type'
		dataType: string
		lineageTag: 17d1a315-1238-4ecd-9b0e-52de715c98df
		summarizeBy: none
		sourceColumn: Contact relationship type

		annotation SummarizationSetBy = Automatic

	column 'Contact first name'
		dataType: string
		lineageTag: d426f713-86b5-4aa0-b94c-6e9c2ac3e79f
		summarizeBy: none
		sourceColumn: Contact first name

		annotation SummarizationSetBy = Automatic

	column 'Contact last name'
		dataType: string
		lineageTag: 638c3e97-6ac6-4668-95d9-0a7170a03634
		summarizeBy: none
		sourceColumn: Contact last name

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 3a15d51e-d50c-40fe-862a-e0f2fd4d1b66
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column 'Mobile Phone'
		dataType: string
		lineageTag: 8f045917-7637-47ce-af16-af4920637fd0
		summarizeBy: none
		sourceColumn: Mobile Phone

		annotation SummarizationSetBy = Automatic

	column 'Other telephone'
		dataType: string
		lineageTag: 882378bc-b69b-4c86-b5ce-65db1f1b117a
		summarizeBy: none
		sourceColumn: Other telephone

		annotation SummarizationSetBy = Automatic

	column 'Emergency contact details'
		dataType: string
		lineageTag: 5e1a680d-0ce3-4b76-8491-20766615830d
		summarizeBy: none
		sourceColumn: Emergency contact details

		annotation SummarizationSetBy = Automatic

	column 'Specific medical conditions'
		dataType: string
		lineageTag: bec64be1-f8a5-44c2-972d-91ad84408f67
		summarizeBy: none
		sourceColumn: Specific medical conditions

		annotation SummarizationSetBy = Automatic

	column 'Any other conditions, allergies or dietary requirements etc'
		dataType: string
		lineageTag: c921448d-52bf-4885-9b8a-17bc78b2193d
		summarizeBy: none
		sourceColumn: Any other conditions, allergies or dietary requirements etc

		annotation SummarizationSetBy = Automatic

	column Disability
		dataType: string
		lineageTag: e075977f-fb69-4f89-9207-8f92fb6e88e2
		summarizeBy: none
		sourceColumn: Disability

		annotation SummarizationSetBy = Automatic

	column Ethnicity
		dataType: string
		lineageTag: abdf332f-98f1-41d1-ac2e-cd1f5103bf0e
		summarizeBy: none
		sourceColumn: Ethnicity

		annotation SummarizationSetBy = Automatic

	column Faith
		dataType: string
		lineageTag: 328e540e-f3b9-49f0-a2ed-01332325af4e
		summarizeBy: none
		sourceColumn: Faith

		annotation SummarizationSetBy = Automatic

	column 'Sexual orientation'
		dataType: string
		lineageTag: 73aa67e0-dadd-4b51-8993-1a044b36ef4e
		summarizeBy: none
		sourceColumn: Sexual orientation

		annotation SummarizationSetBy = Automatic

	column School/College/University
		dataType: string
		lineageTag: 8f5ab7a7-fb9b-4c35-99ba-becd5ca425bf
		summarizeBy: none
		sourceColumn: School/College/University

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 5c6746a2-51c3-46dd-8971-4bf1b2c3ef3e
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column 'Edubase URN'
		dataType: string
		lineageTag: c79b9c3a-9af1-4926-8e26-9f99d08c8a7f
		summarizeBy: none
		sourceColumn: Edubase URN

		annotation SummarizationSetBy = Automatic

	column 'FA number'
		dataType: string
		lineageTag: 388a700f-5260-4da2-b2eb-41546d1a696a
		summarizeBy: none
		sourceColumn: FA number

		annotation SummarizationSetBy = Automatic

	column 'Membership ID/number'
		dataType: string
		lineageTag: 2ed4ae02-5c4f-471c-842f-cca270619306
		summarizeBy: none
		sourceColumn: Membership ID/number

		annotation SummarizationSetBy = Automatic

	column 'Has permission: Media consent'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a467d1a6-226f-4533-ad77-f2fc7b64a119
		summarizeBy: none
		sourceColumn: Has permission: Media consent

		annotation SummarizationSetBy = Automatic

	column 'Has permission: Receive surveys via Upshot'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ede60fc9-9747-4f38-9aa0-3ca26509e53a
		summarizeBy: none
		sourceColumn: Has permission: Receive surveys via Upshot

		annotation SummarizationSetBy = Automatic

	column 'Has permission: Receive emails via Upshot'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4c782951-1f7a-4a3a-afd3-7f1145fe26bf
		summarizeBy: none
		sourceColumn: Has permission: Receive emails via Upshot

		annotation SummarizationSetBy = Automatic

	column Registered
		dataType: dateTime
		formatString: Long Date
		lineageTag: fac311eb-8dd3-4828-a18a-43ab9c243a67
		summarizeBy: none
		sourceColumn: Registered

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Added to Upshot'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d5874b2f-0826-4a15-9195-f6888377c1f4
		summarizeBy: none
		sourceColumn: Added to Upshot

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Added by'
		dataType: string
		lineageTag: d4c10d16-48ff-4408-93d6-b66b2552864f
		summarizeBy: none
		sourceColumn: Added by

		annotation SummarizationSetBy = Automatic

	column 'Added via'
		dataType: string
		lineageTag: 70b070e4-896c-437a-9f6e-c6451655fb0f
		summarizeBy: none
		sourceColumn: Added via

		annotation SummarizationSetBy = Automatic

	column 'Last updated'
		dataType: dateTime
		formatString: Long Date
		lineageTag: cefa1e47-5ba1-45e3-bf60-23e6f8d3dec6
		summarizeBy: none
		sourceColumn: Last updated

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Last updated by'
		dataType: string
		lineageTag: 94ed6fd0-9945-443b-94f6-8a0922a1662d
		summarizeBy: none
		sourceColumn: Last updated by

		annotation SummarizationSetBy = Automatic

	column 'First session in time period'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 78430b2c-bc06-4422-bd4d-3adeb5cd901c
		summarizeBy: none
		sourceColumn: First session in time period

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Last session in time period'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9d30391b-0468-4eee-896d-2364f6538e99
		summarizeBy: none
		sourceColumn: Last session in time period

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Project restrictions'
		dataType: string
		lineageTag: 40db9cf2-eb57-487f-a946-34f9c0bc71ad
		summarizeBy: none
		sourceColumn: Project restrictions

		annotation SummarizationSetBy = Automatic

	column 'NI Number:'
		dataType: string
		lineageTag: a8c2974b-4f88-43a0-9523-388479c4c2ba
		summarizeBy: none
		sourceColumn: NI Number:

		annotation SummarizationSetBy = Automatic

	column 'What is the highest level of education you have completed?'
		dataType: string
		lineageTag: 559bbf3d-a83f-4501-bdc2-8aff25b10cb6
		summarizeBy: none
		sourceColumn: What is the highest level of education you have completed?

		annotation SummarizationSetBy = Automatic

	column 'Do you have any paid work/long term volunteering experience since leaving school?'
		dataType: string
		lineageTag: 14d91424-f528-4b9d-baae-bc18b482261a
		summarizeBy: none
		sourceColumn: Do you have any paid work/long term volunteering experience since leaving school?

		annotation SummarizationSetBy = Automatic

	column 'Do you have a driving licence?'
		dataType: string
		lineageTag: c0729c21-01c8-4d6e-ad05-0ef309f9b99f
		summarizeBy: none
		sourceColumn: Do you have a driving licence?

		annotation SummarizationSetBy = Automatic

	column 'Status at start of program'
		dataType: string
		lineageTag: f9b81ade-421e-4616-9a9c-8be76b2bb36d
		summarizeBy: none
		sourceColumn: Status at start of program

		annotation SummarizationSetBy = Automatic

	column 'How long have you been unemployed?'
		dataType: string
		lineageTag: 6829f53e-34af-4f09-b7e0-9fde9cd62fed
		summarizeBy: none
		sourceColumn: How long have you been unemployed?

		annotation SummarizationSetBy = Automatic

	column 'What area/sector would you like to like to work in?'
		dataType: string
		lineageTag: 04ac6b46-6946-43a3-b392-a7c053d2d4aa
		summarizeBy: none
		sourceColumn: What area/sector would you like to like to work in?

		annotation SummarizationSetBy = Automatic

	column Allergies
		dataType: string
		lineageTag: 9f2e7fac-dbad-4aa5-ac8e-5711181359e3
		summarizeBy: none
		sourceColumn: Allergies

		annotation SummarizationSetBy = Automatic

	column Other
		dataType: string
		lineageTag: dbde6cbc-4985-482a-affe-67b7dbf6c62f
		summarizeBy: none
		sourceColumn: Other

		annotation SummarizationSetBy = Automatic

	column 'Do you personally consider yourself to have a disability, regardless of clinical diagnosis?'
		dataType: string
		lineageTag: 57eb4929-73d3-4e00-9f34-3cf2df4afa6b
		summarizeBy: none
		sourceColumn: Do you personally consider yourself to have a disability, regardless of clinical diagnosis?

		annotation SummarizationSetBy = Automatic

	column 'Do you personally consider yourself to be transgender?'
		dataType: string
		lineageTag: 36966f53-80c8-4836-a8c6-47a239046343
		summarizeBy: none
		sourceColumn: Do you personally consider yourself to be transgender?

		annotation SummarizationSetBy = Automatic

	column 'Please indicate if you have any of the following neurodivergent conditions (select all that apply):'
		dataType: string
		lineageTag: 7e37e352-3286-4755-a8a1-c0e9f98c0f9e
		summarizeBy: none
		sourceColumn: Please indicate if you have any of the following neurodivergent conditions (select all that apply):

		annotation SummarizationSetBy = Automatic

	column 'Do you have access to the following types of healthcare services?'
		dataType: string
		lineageTag: 0b269b4e-ed69-40b0-ad22-1c34c2909198
		summarizeBy: none
		sourceColumn: Do you have access to the following types of healthcare services?

		annotation SummarizationSetBy = Automatic

	column 'Are you care experienced?'
		dataType: string
		lineageTag: 7c9f16ec-4f33-427c-92aa-d38c376e2442
		summarizeBy: none
		sourceColumn: Are you care experienced?

		annotation SummarizationSetBy = Automatic

	column 'Where is your PA based?'
		dataType: string
		lineageTag: 3973b6c1-d1e8-4758-9d25-67c66e1e7c0c
		summarizeBy: none
		sourceColumn: Where is your PA based?

		annotation SummarizationSetBy = Automatic

	column Barriers
		dataType: string
		lineageTag: ddfdb9c3-c1ff-4641-b093-6a53ea3e3b4d
		summarizeBy: none
		sourceColumn: Barriers

		annotation SummarizationSetBy = Automatic

	column 'If any of the options on ''Barriers to Employment'' said please state, list detail here:'
		dataType: string
		lineageTag: 3b10ec6c-bea2-4f82-b6c1-53b4007321e4
		summarizeBy: none
		sourceColumn: If any of the options on 'Barriers to Employment' said please state, list detail here:

		annotation SummarizationSetBy = Automatic

	column Benefits:
		dataType: string
		lineageTag: 5cbd24c6-758b-45f2-a61e-453ddab58cce
		summarizeBy: none
		sourceColumn: Benefits:

		annotation SummarizationSetBy = Automatic

	column 'Date of Claim for above:'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7c8b7b08-2716-48d2-8251-b928dfc3dba2
		summarizeBy: none
		sourceColumn: Date of Claim for above:

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Other benefits:'
		dataType: string
		lineageTag: 918f673b-9fd7-473d-a502-c0244b1c1c5f
		summarizeBy: none
		sourceColumn: Other benefits:

		annotation SummarizationSetBy = Automatic

	column 'Living Arrangements:'
		dataType: string
		lineageTag: d44de446-b96f-4d56-97d2-c0e4783ab2e3
		summarizeBy: none
		sourceColumn: Living Arrangements:

		annotation SummarizationSetBy = Automatic

	column 'Are you working with any other service?'
		dataType: string
		lineageTag: bc74b839-b0ee-41e2-92fe-86878a6f07c4
		summarizeBy: none
		sourceColumn: Are you working with any other service?

		annotation SummarizationSetBy = Automatic

	column 'If other services worked with, please state:'
		dataType: string
		lineageTag: 453ce871-ab05-489d-90de-99b70389477e
		summarizeBy: none
		sourceColumn: If other services worked with, please state:

		annotation SummarizationSetBy = Automatic

	column 'Which Services?'
		dataType: string
		lineageTag: e34281e5-6d3f-4633-a892-8823777cf279
		summarizeBy: none
		sourceColumn: Which Services?

		annotation SummarizationSetBy = Automatic

	column 'Referred from:'
		dataType: string
		lineageTag: c44e3c04-0ec1-492b-bac0-cc12aa42eac6
		summarizeBy: none
		sourceColumn: Referred from:

		annotation SummarizationSetBy = Automatic

	column 'Job Center referred by?'
		dataType: string
		lineageTag: 7c4f7ad9-6fc1-4177-a5da-5e45c6b99979
		summarizeBy: none
		sourceColumn: Job Center referred by?

		annotation SummarizationSetBy = Automatic

	column Notes:
		dataType: string
		lineageTag: 82f54b7e-6a4b-421e-9a49-bc7e11767c27
		summarizeBy: none
		sourceColumn: Notes:

		annotation SummarizationSetBy = Automatic

	column 'Project(s) involved in:'
		dataType: string
		lineageTag: e91dfda2-649d-436b-bf37-b42f1816d115
		summarizeBy: none
		sourceColumn: Project(s) involved in:

		annotation SummarizationSetBy = Automatic

	column 'Benny Walker Worker'
		dataType: string
		lineageTag: 16b8abab-4e43-49d7-8dd4-a31bbd54a26b
		summarizeBy: none
		sourceColumn: Benny Walker Worker

		annotation SummarizationSetBy = Automatic

	column 'Forging Futures Worker'
		dataType: string
		lineageTag: b4402241-3cb5-4587-b4d9-ebb4f959639f
		summarizeBy: none
		sourceColumn: Forging Futures Worker

		annotation SummarizationSetBy = Automatic

	column 'Maintaining Relationships Worker'
		dataType: string
		lineageTag: cd62aefe-5fa2-48f9-aabf-83f85ffc146f
		summarizeBy: none
		sourceColumn: Maintaining Relationships Worker

		annotation SummarizationSetBy = Automatic

	column 'Leaving Care Worker'
		dataType: string
		lineageTag: 928d906e-d8ea-43d6-9cb3-1659336a8264
		summarizeBy: none
		sourceColumn: Leaving Care Worker

		annotation SummarizationSetBy = Automatic

	column 'Referral Status'
		dataType: string
		lineageTag: ad37b8cb-85ef-44dd-accb-c51ffb74246d
		summarizeBy: none
		sourceColumn: Referral Status

		annotation SummarizationSetBy = Automatic

	column 'Signposted to:'
		dataType: string
		lineageTag: 91b89745-6e0d-490a-b71d-354d178e7cc8
		summarizeBy: none
		sourceColumn: Signposted to:

		annotation SummarizationSetBy = Automatic

	partition DOPeople = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://cyacumbria.sharepoint.com/sites/CYAAllStaff/Shared%20Documents/General/Data%20Team/Staff%20Cards/CYA%20Staff%20Card%20POW%20BI%20V2.xlsx"), null, true),
				    DOPeople_Table = Source{[Item="DOPeople",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(DOPeople_Table,{{"Upshot ID", type text}, {"Status", type text}, {"Archived on", type date}, {"First Name", type text}, {"Last Name", type text}, {"Nickname", type text}, {"Gender", type text}, {"Date of Birth", type date}, {"Age", Int64.Type}, {"Identifying notes", type text}, {"Address line 1", type text}, {"Address line 2", type text}, {"Address line 3", type text}, {"Town/City", type text}, {"County", type text}, {"Postcode", type text}, {"Longitude", type number}, {"Latitude", type number}, {"Strategic Authority", type text}, {"County or Unitary Authority", type text}, {"Local Authority", type text}, {"Constituency", type text}, {"Ward", type text}, {"LSOA code", type text}, {"IMD percent", Int64.Type}, {"Contact relationship type", type text}, {"Contact first name", type text}, {"Contact last name", type text}, {"Email", type text}, {"Mobile Phone", type text}, {"Other telephone", type text}, {"Emergency contact details", type text}, {"Specific medical conditions", type text}, {"Any other conditions, allergies or dietary requirements etc", type text}, {"Disability", type text}, {"Ethnicity", type text}, {"Faith", type text}, {"Sexual orientation", type text}, {"School/College/University", type text}, {"Type", type text}, {"Edubase URN", type text}, {"FA number", type text}, {"Membership ID/number", type text}, {"Has permission: Media consent", type logical}, {"Has permission: Receive surveys via Upshot", type logical}, {"Has permission: Receive emails via Upshot", type logical}, {"Registered", type date}, {"Added to Upshot", type date}, {"Added by", type text}, {"Added via", type text}, {"Last updated", type date}, {"Last updated by", type text}, {"First session in time period", type date}, {"Last session in time period", type date}, {"Project restrictions", type text}, {"NI Number:", type text}, {"What is the highest level of education you have completed?", type text}, {"Do you have any paid work/long term volunteering experience since leaving school?", type text}, {"Do you have a driving licence?", type text}, {"Status at start of program", type text}, {"How long have you been unemployed?", type text}, {"What area/sector would you like to like to work in?", type text}, {"Allergies", type text}, {"Other", type text}, {"Do you personally consider yourself to have a disability, regardless of clinical diagnosis?", type text}, {"Do you personally consider yourself to be transgender?", type text}, {"Please indicate if you have any of the following neurodivergent conditions (select all that apply):", type text}, {"Do you have access to the following types of healthcare services?", type text}, {"Are you care experienced?", type text}, {"Where is your PA based?", type text}, {"Barriers", type text}, {"If any of the options on 'Barriers to Employment' said please state, list detail here:", type text}, {"Benefits:", type text}, {"Date of Claim for above:", type date}, {"Other benefits:", type text}, {"Living Arrangements:", type text}, {"Are you working with any other service?", type text}, {"If other services worked with, please state:", type text}, {"Which Services?", type text}, {"Referred from:", type text}, {"Job Center referred by?", type text}, {"Notes:", type text}, {"Project(s) involved in:", type text}, {"Benny Walker Worker", type text}, {"Forging Futures Worker", type text}, {"Maintaining Relationships Worker", type text}, {"Leaving Care Worker", type text}, {"Referral Status", type text}, {"Signposted to:", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

