table DOTLE
	lineageTag: 43bf7db4-51f1-4809-8b94-6f53b672c0de

	column 'Upshot ID'
		dataType: string
		lineageTag: b4414f0f-c9f3-4304-a019-700459c98de1
		summarizeBy: none
		sourceColumn: Upshot ID

		annotation SummarizationSetBy = Automatic

	column 'First name'
		dataType: string
		lineageTag: e8c5496b-0749-4d7e-9f32-37db0ef4e622
		summarizeBy: none
		sourceColumn: First name

		annotation SummarizationSetBy = Automatic

	column 'Last name'
		dataType: string
		lineageTag: 1624cc52-eb87-4cbf-91c4-c1036ef5679d
		summarizeBy: none
		sourceColumn: Last name

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 805ffe9c-ab7b-452f-8064-f87db6280d43
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Event ID'
		dataType: string
		lineageTag: 3b33cb82-8f33-4f5a-ae41-48d1cbee7e4d
		summarizeBy: none
		sourceColumn: Event ID

		annotation SummarizationSetBy = Automatic

	column 'Event date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e4b1f8dc-9638-4f7d-9f04-14ec519b6b1b
		summarizeBy: none
		sourceColumn: Event date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Expiry date'
		dataType: string
		lineageTag: a01ee07f-74d5-4a7c-8943-9042d283db5a
		summarizeBy: none
		sourceColumn: Expiry date

		annotation SummarizationSetBy = Automatic

	column 'Event type'
		dataType: string
		lineageTag: ee9978e0-fa55-4a94-b408-45cfbce430b7
		summarizeBy: none
		sourceColumn: Event type

		annotation SummarizationSetBy = Automatic

	column 'Event value'
		dataType: string
		lineageTag: 93f2fa4c-6997-4baa-af39-f15ee4df056b
		summarizeBy: none
		sourceColumn: Event value

		annotation SummarizationSetBy = Automatic

	column Notes
		dataType: string
		lineageTag: b2d1146b-f72e-48fb-bac1-da4c0bc1a9d1
		summarizeBy: none
		sourceColumn: Notes

		annotation SummarizationSetBy = Automatic

	column Project
		dataType: string
		lineageTag: 580787f1-f9c9-40dc-98de-7c3c3d7e9f3e
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column Activity
		dataType: string
		lineageTag: e26397f2-6f69-4f04-8e9e-2f4727e12cc3
		summarizeBy: none
		sourceColumn: Activity

		annotation SummarizationSetBy = Automatic

	column 'Activity Group'
		dataType: string
		lineageTag: d363a8e7-2c1e-49e5-809c-1a3031109bfd
		summarizeBy: none
		sourceColumn: Activity Group

		annotation SummarizationSetBy = Automatic

	column 'Activity Type'
		dataType: string
		lineageTag: 198b374e-adae-4c06-a57e-414408c2dbd6
		summarizeBy: none
		sourceColumn: Activity Type

		annotation SummarizationSetBy = Automatic

	column 'Recording user first name'
		dataType: string
		lineageTag: 4c142959-2a29-4337-8449-ecd374127b9e
		summarizeBy: none
		sourceColumn: Recording user first name

		annotation SummarizationSetBy = Automatic

	column 'Recording user last name'
		dataType: string
		lineageTag: 33d9b14a-d2c9-4aba-b775-bcd1779c0f2f
		summarizeBy: none
		sourceColumn: Recording user last name

		annotation SummarizationSetBy = Automatic

	column 'Date recorded'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5c490663-cba8-464b-a5d8-1257d6bba041
		summarizeBy: none
		sourceColumn: Date recorded

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Time recorded'
		dataType: dateTime
		formatString: Long Time
		lineageTag: a8c3c90d-ed4e-47ac-81d5-589b1a81546f
		summarizeBy: none
		sourceColumn: Time recorded

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition DOTLE = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://cyacumbria.sharepoint.com/sites/CYAAllStaff/Shared%20Documents/General/Data%20Team/Staff%20Cards/CYA%20Staff%20Card%20POW%20BI%20V2.xlsx"), null, true),
				    DOTLE_Table = Source{[Item="DOTLE",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(DOTLE_Table,{{"Upshot ID", type text}, {"First name", type text}, {"Last name", type text}, {"Status", type text}, {"Event ID", type text}, {"Event date", type date}, {"Expiry date", type text}, {"Event type", type text}, {"Event value", type text}, {"Notes", type text}, {"Project", type text}, {"Activity", type text}, {"Activity Group", type text}, {"Activity Type", type text}, {"Recording user first name", type text}, {"Recording user last name", type text}, {"Date recorded", type date}, {"Time recorded", type time}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

