table InfraPeople
	lineageTag: a81e6c8a-3e7c-4ea0-8fe8-0cc24eddf3a2

	column 'Upshot ID'
		dataType: string
		lineageTag: 26f9d7b4-ec52-478c-a151-940f09521458
		summarizeBy: none
		sourceColumn: Upshot ID

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: d57843be-856c-4c63-b30d-a784ee7da3f0
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Archived on'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 038ce257-e548-4d99-8c73-8662ae17dfdf
		summarizeBy: none
		sourceColumn: Archived on

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'First Name'
		dataType: string
		lineageTag: 9c6ddd74-3876-458d-80ad-df4abce960ef
		summarizeBy: none
		sourceColumn: First Name

		annotation SummarizationSetBy = Automatic

	column 'Last Name'
		dataType: string
		lineageTag: a86542eb-02ac-4d53-9bbe-e689ee9cd17b
		summarizeBy: none
		sourceColumn: Last Name

		annotation SummarizationSetBy = Automatic

	column Nickname
		dataType: string
		lineageTag: a915fbdd-902a-4975-9a40-7a2f43d18b2b
		summarizeBy: none
		sourceColumn: Nickname

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: b618a387-8e77-41ff-89fb-5c536ebe8f08
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column 'Date of Birth'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 64013213-ef05-48ce-aabb-1aef6e3beecd
		summarizeBy: none
		sourceColumn: Date of Birth

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Age
		dataType: int64
		formatString: 0
		lineageTag: d1cd2b91-46ef-4d0d-8d40-0a12bdc3298e
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column 'Identifying notes'
		dataType: string
		lineageTag: 47fc2e30-44ca-407f-bd8a-a047dc254560
		summarizeBy: none
		sourceColumn: Identifying notes

		annotation SummarizationSetBy = Automatic

	column 'Address line 1'
		dataType: string
		lineageTag: 81088df5-fe48-4d77-b0d4-2cadfc5db288
		summarizeBy: none
		sourceColumn: Address line 1

		annotation SummarizationSetBy = Automatic

	column 'Address line 2'
		dataType: string
		lineageTag: dc9bfb50-2cc5-40fb-8553-1365f57e7c84
		summarizeBy: none
		sourceColumn: Address line 2

		annotation SummarizationSetBy = Automatic

	column 'Address line 3'
		dataType: string
		lineageTag: e637b64d-b16f-4d47-880b-bd3619cbf2d1
		summarizeBy: none
		sourceColumn: Address line 3

		annotation SummarizationSetBy = Automatic

	column Town/City
		dataType: string
		lineageTag: d5e392b6-afcf-45dd-b7c5-8ffcec0e5e1e
		summarizeBy: none
		sourceColumn: Town/City

		annotation SummarizationSetBy = Automatic

	column County
		dataType: string
		lineageTag: a9a1d6ef-7d70-4ecd-a553-739f49009a65
		summarizeBy: none
		sourceColumn: County

		annotation SummarizationSetBy = Automatic

	column Postcode
		dataType: string
		lineageTag: 72fe6ed1-be67-4191-b78a-85aec9f5b8fc
		summarizeBy: none
		sourceColumn: Postcode

		annotation SummarizationSetBy = Automatic

	column Longitude
		dataType: double
		lineageTag: ed119e04-1ccd-44c7-84a8-a60d80dfb18d
		summarizeBy: sum
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Latitude
		dataType: double
		lineageTag: cef0a24a-263e-40a0-a5e6-ece9f2ad7ba6
		summarizeBy: sum
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Strategic Authority'
		dataType: string
		lineageTag: 32410ac7-1704-448c-bb90-a8d6eb21e8cc
		summarizeBy: none
		sourceColumn: Strategic Authority

		annotation SummarizationSetBy = Automatic

	column 'County or Unitary Authority'
		dataType: string
		lineageTag: 223fc41f-c04e-45ed-85d8-8fc2972268e6
		summarizeBy: none
		sourceColumn: County or Unitary Authority

		annotation SummarizationSetBy = Automatic

	column 'Local Authority'
		dataType: string
		lineageTag: 25f20a08-8130-4446-b175-2eaef717ce5a
		summarizeBy: none
		sourceColumn: Local Authority

		annotation SummarizationSetBy = Automatic

	column Constituency
		dataType: string
		lineageTag: e1cf1662-3454-4470-b9bb-a5df3fdcd2eb
		summarizeBy: none
		sourceColumn: Constituency

		annotation SummarizationSetBy = Automatic

	column Ward
		dataType: string
		lineageTag: 44ca27b5-8e54-4d65-af9b-c53f919ab5b8
		summarizeBy: none
		sourceColumn: Ward

		annotation SummarizationSetBy = Automatic

	column 'LSOA code'
		dataType: string
		lineageTag: 91567d18-292b-4080-afda-b651bd87d4bb
		summarizeBy: none
		sourceColumn: LSOA code

		annotation SummarizationSetBy = Automatic

	column 'IMD percent'
		dataType: int64
		formatString: 0
		lineageTag: a79b41af-0ff7-4eaa-8f58-e55318deb761
		summarizeBy: sum
		sourceColumn: IMD percent

		annotation SummarizationSetBy = Automatic

	column 'Contact relationship type'
		dataType: string
		lineageTag: ff9e4657-fd47-453a-83d7-13f597424090
		summarizeBy: none
		sourceColumn: Contact relationship type

		annotation SummarizationSetBy = Automatic

	column 'Contact first name'
		dataType: string
		lineageTag: 61a94e85-9871-4496-8590-ff940f5d7abf
		summarizeBy: none
		sourceColumn: Contact first name

		annotation SummarizationSetBy = Automatic

	column 'Contact last name'
		dataType: string
		lineageTag: 2392db8d-d205-4307-908b-06a6b3a342f8
		summarizeBy: none
		sourceColumn: Contact last name

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 694fdd14-4b1e-462e-9743-d0d4be56b2d0
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column 'Mobile Phone'
		dataType: string
		lineageTag: 508d997f-6626-4380-a8b9-c00ce941ef9e
		summarizeBy: none
		sourceColumn: Mobile Phone

		annotation SummarizationSetBy = Automatic

	column 'Other telephone'
		dataType: string
		lineageTag: 3fbde23e-6b42-4dc7-9fd4-10c03258c056
		summarizeBy: none
		sourceColumn: Other telephone

		annotation SummarizationSetBy = Automatic

	column 'Emergency contact details'
		dataType: string
		lineageTag: 4c9b0410-8771-4903-9e8f-e7b4151766c8
		summarizeBy: none
		sourceColumn: Emergency contact details

		annotation SummarizationSetBy = Automatic

	column 'Specific medical conditions'
		dataType: string
		lineageTag: e58ca2d3-b632-4c5f-b32b-63d450fe58e2
		summarizeBy: none
		sourceColumn: Specific medical conditions

		annotation SummarizationSetBy = Automatic

	column 'Any other conditions, allergies or dietary requirements etc'
		dataType: string
		lineageTag: 191b1884-19d6-4fe0-9dc1-423ab1e728d2
		summarizeBy: none
		sourceColumn: Any other conditions, allergies or dietary requirements etc

		annotation SummarizationSetBy = Automatic

	column Disability
		dataType: string
		lineageTag: fc3e6e6f-7112-4660-ad71-443143797c50
		summarizeBy: none
		sourceColumn: Disability

		annotation SummarizationSetBy = Automatic

	column Ethnicity
		dataType: string
		lineageTag: c043b8e7-6d22-42ea-8b78-d5d5eb4881f0
		summarizeBy: none
		sourceColumn: Ethnicity

		annotation SummarizationSetBy = Automatic

	column Faith
		dataType: string
		lineageTag: b7821ca6-8187-4041-bd29-0439b7775f3d
		summarizeBy: none
		sourceColumn: Faith

		annotation SummarizationSetBy = Automatic

	column 'Sexual orientation'
		dataType: string
		lineageTag: a7024dc1-8b79-4fa1-9aaf-ad0d02530148
		summarizeBy: none
		sourceColumn: Sexual orientation

		annotation SummarizationSetBy = Automatic

	column School/College/University
		dataType: string
		lineageTag: 6cd2c501-29de-4551-8f66-37002e1e8c7d
		summarizeBy: none
		sourceColumn: School/College/University

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 5a729051-2ba1-468c-916f-b1d84fd0b2af
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column 'Edubase URN'
		dataType: string
		lineageTag: 9d2ae82e-afe5-431f-9436-ab6df6be9593
		summarizeBy: none
		sourceColumn: Edubase URN

		annotation SummarizationSetBy = Automatic

	column 'FA number'
		dataType: string
		lineageTag: d1033597-b8a7-4c0a-bdb1-04edecd1b88b
		summarizeBy: none
		sourceColumn: FA number

		annotation SummarizationSetBy = Automatic

	column 'Membership ID/number'
		dataType: string
		lineageTag: 938c723e-a21d-4f5e-a3fd-4a65da0530cc
		summarizeBy: none
		sourceColumn: Membership ID/number

		annotation SummarizationSetBy = Automatic

	column 'Has permission: Media consent'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: bb92f23d-3b30-4600-b052-8c722edf5d7e
		summarizeBy: none
		sourceColumn: Has permission: Media consent

		annotation SummarizationSetBy = Automatic

	column 'Has permission: Receive surveys via Upshot'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 83e5bbac-4cab-48ec-8105-d48b304c7bf9
		summarizeBy: none
		sourceColumn: Has permission: Receive surveys via Upshot

		annotation SummarizationSetBy = Automatic

	column 'Has permission: Receive emails via Upshot'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 619c5835-9308-4f41-bcc8-25d7bc3429e1
		summarizeBy: none
		sourceColumn: Has permission: Receive emails via Upshot

		annotation SummarizationSetBy = Automatic

	column Registered
		dataType: dateTime
		formatString: Long Date
		lineageTag: fc788b07-174b-4463-92ce-582caf017630
		summarizeBy: none
		sourceColumn: Registered

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Added to Upshot'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f11e10d1-74c8-4367-8759-d644af0e9a0d
		summarizeBy: none
		sourceColumn: Added to Upshot

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Added by'
		dataType: string
		lineageTag: 72415097-e86c-4d1f-ae02-6df1d159f451
		summarizeBy: none
		sourceColumn: Added by

		annotation SummarizationSetBy = Automatic

	column 'Added via'
		dataType: string
		lineageTag: b712a2f0-6326-4a3f-a101-7bf3ed5221f9
		summarizeBy: none
		sourceColumn: Added via

		annotation SummarizationSetBy = Automatic

	column 'Last updated'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b6306b54-f358-4f09-9e06-b3f81b3cd13d
		summarizeBy: none
		sourceColumn: Last updated

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Last updated by'
		dataType: string
		lineageTag: 641e1066-e574-404f-ae58-8e9debc4270e
		summarizeBy: none
		sourceColumn: Last updated by

		annotation SummarizationSetBy = Automatic

	column 'First session in time period'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1a704433-798b-4900-ac15-b8ad99150b50
		summarizeBy: none
		sourceColumn: First session in time period

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Last session in time period'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8bf9d6d0-9b38-4932-baf2-47ef651c1553
		summarizeBy: none
		sourceColumn: Last session in time period

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Type of Profile:'
		dataType: string
		lineageTag: aea107c0-02c1-468e-82b7-87417cc96d17
		summarizeBy: none
		sourceColumn: Type of Profile:

		annotation SummarizationSetBy = Automatic

	column 'Project(s) involved in:'
		dataType: string
		lineageTag: a9ebaa44-0b33-4978-b21f-f3c47afce8eb
		summarizeBy: none
		sourceColumn: Project(s) involved in:

		annotation SummarizationSetBy = Automatic

	column Sector:
		dataType: string
		lineageTag: 105524e3-9c52-47a4-99dd-d43e98e2649e
		summarizeBy: none
		sourceColumn: Sector:

		annotation SummarizationSetBy = Automatic

	column 'What does your organisation offer?'
		dataType: string
		lineageTag: dd3f4bf8-b05a-4185-8437-f56d9173a429
		summarizeBy: none
		sourceColumn: What does your organisation offer?

		annotation SummarizationSetBy = Automatic

	column Area(s):
		dataType: string
		lineageTag: dca026c6-0178-4970-97cb-494b2ef15aa8
		summarizeBy: none
		sourceColumn: Area(s):

		annotation SummarizationSetBy = Automatic

	column 'What age groups do you support?'
		dataType: string
		lineageTag: 7d8170c6-f11f-4805-881b-7dbec6dd4e11
		summarizeBy: none
		sourceColumn: What age groups do you support?

		annotation SummarizationSetBy = Automatic

	column 'Organisations Notes'
		dataType: string
		lineageTag: 24bc00af-8005-4068-861f-3cc64ea629cd
		summarizeBy: none
		sourceColumn: Organisations Notes

		annotation SummarizationSetBy = Automatic

	column 'Charity/Company Number'
		dataType: string
		lineageTag: 32fa851a-183b-494d-b442-e577d3dfed5c
		summarizeBy: none
		sourceColumn: Charity/Company Number

		annotation SummarizationSetBy = Automatic

	column 'What is the total annual income of your organisation?'
		dataType: string
		lineageTag: 26f2788c-f7f6-42b8-9b7e-dd7518288216
		summarizeBy: none
		sourceColumn: What is the total annual income of your organisation?

		annotation SummarizationSetBy = Automatic

	column 'How long does the support term last?'
		dataType: string
		lineageTag: 7bb66431-07ca-4173-8a9f-d2eca5d77eca
		summarizeBy: none
		sourceColumn: How long does the support term last?

		annotation SummarizationSetBy = Automatic

	column 'Where did you learn about this organisation?'
		dataType: string
		lineageTag: aedec381-f88a-4e77-8210-399934a94cea
		summarizeBy: none
		sourceColumn: Where did you learn about this organisation?

		annotation SummarizationSetBy = Automatic

	column 'Response time'
		dataType: string
		lineageTag: 928c1af6-e4a2-44df-8b60-e217215ff90b
		summarizeBy: none
		sourceColumn: Response time

		annotation SummarizationSetBy = Automatic

	partition InfraPeople = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://cyacumbria.sharepoint.com/sites/CYAAllStaff/Shared%20Documents/General/Data%20Team/Staff%20Cards/CYA%20Staff%20Card%20POW%20BI%20V2.xlsx"), null, true),
				    InfraPeople_Table = Source{[Item="InfraPeople",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(InfraPeople_Table,{{"Upshot ID", type text}, {"Status", type text}, {"Archived on", type date}, {"First Name", type text}, {"Last Name", type text}, {"Nickname", type text}, {"Gender", type text}, {"Date of Birth", type date}, {"Age", Int64.Type}, {"Identifying notes", type any}, {"Address line 1", type text}, {"Address line 2", type text}, {"Address line 3", type text}, {"Town/City", type text}, {"County", type text}, {"Postcode", type text}, {"Longitude", type number}, {"Latitude", type number}, {"Strategic Authority", type text}, {"County or Unitary Authority", type text}, {"Local Authority", type text}, {"Constituency", type text}, {"Ward", type text}, {"LSOA code", type text}, {"IMD percent", Int64.Type}, {"Contact relationship type", type text}, {"Contact first name", type text}, {"Contact last name", type text}, {"Email", type text}, {"Mobile Phone", type text}, {"Other telephone", type text}, {"Emergency contact details", type text}, {"Specific medical conditions", type text}, {"Any other conditions, allergies or dietary requirements etc", type text}, {"Disability", type text}, {"Ethnicity", type text}, {"Faith", type text}, {"Sexual orientation", type text}, {"School/College/University", type text}, {"Type", type text}, {"Edubase URN", type text}, {"FA number", type text}, {"Membership ID/number", type text}, {"Has permission: Media consent", type logical}, {"Has permission: Receive surveys via Upshot", type logical}, {"Has permission: Receive emails via Upshot", type logical}, {"Registered", type date}, {"Added to Upshot", type date}, {"Added by", type text}, {"Added via", type text}, {"Last updated", type date}, {"Last updated by", type text}, {"First session in time period", type date}, {"Last session in time period", type date}, {"Type of Profile:", type text}, {"Project(s) involved in:", type text}, {"Sector:", type text}, {"What does your organisation offer?", type text}, {"Area(s):", type text}, {"What age groups do you support?", type text}, {"Organisations Notes", type text}, {"Charity/Company Number", type text}, {"What is the total annual income of your organisation?", type text}, {"How long does the support term last?", type text}, {"Where did you learn about this organisation?", type text}, {"Response time", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

