table InfraAttendance
	lineageTag: 808eeda7-0d66-4763-95b3-056794a76bce

	column Project
		dataType: string
		lineageTag: 4414f4c7-643c-417b-a8db-dcbbda6c80f7
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column 'Activity type'
		dataType: string
		lineageTag: 96f877e9-f554-4021-b496-a51d506ea18c
		summarizeBy: none
		sourceColumn: Activity type

		annotation SummarizationSetBy = Automatic

	column 'Activity group'
		dataType: string
		lineageTag: 29ab8ee3-2083-4821-b2f1-c67e10adc9c9
		summarizeBy: none
		sourceColumn: Activity group

		annotation SummarizationSetBy = Automatic

	column 'Activity group ID'
		dataType: string
		lineageTag: 5c59a396-8dd6-44d7-bf5a-cdbb67cdf7c1
		summarizeBy: none
		sourceColumn: Activity group ID

		annotation SummarizationSetBy = Automatic

	column 'Activity ID'
		dataType: string
		lineageTag: be02195f-b2b0-4c35-b54e-4f6fe4a4daf4
		summarizeBy: none
		sourceColumn: Activity ID

		annotation SummarizationSetBy = Automatic

	column Activity
		dataType: string
		lineageTag: a5b23eef-213d-4ed4-a536-8d580c925de7
		summarizeBy: none
		sourceColumn: Activity

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: 781167bd-1520-4094-9899-23606e11c82b
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: feb00681-1a0c-485b-acdb-ef012c0eef01
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column 'Location ID'
		dataType: string
		lineageTag: b06f4a7c-9c16-4a98-9c97-2fee1c50b2d1
		summarizeBy: none
		sourceColumn: Location ID

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: f0a245c5-f6e1-4b3d-8502-2d8dd4f504e9
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Start time'
		dataType: dateTime
		formatString: Long Time
		lineageTag: d9e5a508-e625-4876-8ab7-c2f94e3ad995
		summarizeBy: none
		sourceColumn: Start time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Duration (hrs)'
		dataType: int64
		formatString: 0
		lineageTag: 93fc455d-9ee8-4406-9523-679c86221a14
		summarizeBy: sum
		sourceColumn: Duration (hrs)

		annotation SummarizationSetBy = Automatic

	column 'Session registrar'
		dataType: string
		lineageTag: 668b185c-0192-430c-9dff-f2de05d3b93d
		summarizeBy: none
		sourceColumn: Session registrar

		annotation SummarizationSetBy = Automatic

	column Tags
		dataType: string
		lineageTag: ec562524-234e-40df-8a14-0962168295e0
		summarizeBy: none
		sourceColumn: Tags

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 9794fcd8-4918-47f9-9ba5-e71d61a65524
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Created on'
		dataType: dateTime
		formatString: General Date
		lineageTag: 74956963-2d17-4396-8c24-ab726fd92c56
		summarizeBy: none
		sourceColumn: Created on

		annotation SummarizationSetBy = Automatic

	column 'Created by'
		dataType: string
		lineageTag: d3911967-eaf1-4f56-92ae-f6176dc8f1c7
		summarizeBy: none
		sourceColumn: Created by

		annotation SummarizationSetBy = Automatic

	column 'Edited on'
		dataType: dateTime
		formatString: General Date
		lineageTag: c6d7fe3f-581d-486b-91d5-ab71da5d730f
		summarizeBy: none
		sourceColumn: Edited on

		annotation SummarizationSetBy = Automatic

	column 'Edited by'
		dataType: string
		lineageTag: 563f9df3-c4a7-47c9-88e3-ae82d4692ba0
		summarizeBy: none
		sourceColumn: Edited by

		annotation SummarizationSetBy = Automatic

	column 'Session ID'
		dataType: string
		lineageTag: 5cbde697-09d6-4f87-870c-5cea57975bbf
		summarizeBy: none
		sourceColumn: Session ID

		annotation SummarizationSetBy = Automatic

	column 'Session notes'
		dataType: string
		lineageTag: 8378d4bf-d614-4fa8-97b1-31c44b8f9ef7
		summarizeBy: none
		sourceColumn: Session notes

		annotation SummarizationSetBy = Automatic

	column 'Attendee type'
		dataType: string
		lineageTag: 18fbc4e2-9224-429c-89ec-615859a296f5
		summarizeBy: none
		sourceColumn: Attendee type

		annotation SummarizationSetBy = Automatic

	column 'First name'
		dataType: string
		lineageTag: 9c106d1a-1ea4-4f5d-b4e0-31d6a5725979
		summarizeBy: none
		sourceColumn: First name

		annotation SummarizationSetBy = Automatic

	column 'Last name'
		dataType: string
		lineageTag: 559f0e1c-f8ab-43d3-b774-1fd1fbc22ab4
		summarizeBy: none
		sourceColumn: Last name

		annotation SummarizationSetBy = Automatic

	column Nickname
		dataType: string
		lineageTag: c63dbd73-eab9-49c3-8ae2-a0b1c4d126c1
		summarizeBy: none
		sourceColumn: Nickname

		annotation SummarizationSetBy = Automatic

	column 'Attendee ID'
		dataType: string
		lineageTag: 2d99dfee-b210-48cb-91af-0482067bef8a
		summarizeBy: none
		sourceColumn: Attendee ID

		annotation SummarizationSetBy = Automatic

	column 'Attendee status'
		dataType: string
		lineageTag: cb344908-713a-420f-bdc8-fafabef8b173
		summarizeBy: none
		sourceColumn: Attendee status

		annotation SummarizationSetBy = Automatic

	column 'Archived on'
		dataType: dateTime
		formatString: General Date
		lineageTag: b7b2535a-dca4-412d-a290-0835a2b9a7b2
		summarizeBy: none
		sourceColumn: Archived on

		annotation SummarizationSetBy = Automatic

	partition InfraAttendance = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://cyacumbria.sharepoint.com/sites/CYAAllStaff/Shared%20Documents/General/Data%20Team/Staff%20Cards/CYA%20Staff%20Card%20POW%20BI%20V2.xlsx"), null, true),
				    InfraAttendance_Table = Source{[Item="InfraAttendance",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(InfraAttendance_Table,{{"Project", type text}, {"Activity type", type text}, {"Activity group", type text}, {"Activity group ID", type text}, {"Activity ID", type text}, {"Activity", type text}, {"Title", type text}, {"Location", type text}, {"Location ID", type text}, {"Date", type date}, {"Start time", type time}, {"Duration (hrs)", Int64.Type}, {"Session registrar", type text}, {"Tags", type any}, {"Status", type text}, {"Created on", type datetime}, {"Created by", type text}, {"Edited on", type datetime}, {"Edited by", type text}, {"Session ID", type text}, {"Session notes", type any}, {"Attendee type", type text}, {"First name", type text}, {"Last name", type text}, {"Nickname", type any}, {"Attendee ID", type text}, {"Attendee status", type text}, {"Archived on", type datetime}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

