table InfraTLE
	lineageTag: cfa2e334-5119-443e-90aa-484f68bc37c2

	column 'Upshot ID'
		dataType: string
		lineageTag: 2b38b395-70ed-41a2-9556-f6bdea4c7b01
		summarizeBy: none
		sourceColumn: Upshot ID

		annotation SummarizationSetBy = Automatic

	column 'First name'
		dataType: string
		lineageTag: 3d309467-ecc6-4036-8dd2-2b7b52df2478
		summarizeBy: none
		sourceColumn: First name

		annotation SummarizationSetBy = Automatic

	column 'Last name'
		dataType: string
		lineageTag: 7d0e11ad-20ab-44dc-b24f-875b2e6d40ae
		summarizeBy: none
		sourceColumn: Last name

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 8bf3f113-7ff4-4a67-adfb-49e22e2f8a47
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Event ID'
		dataType: string
		lineageTag: 1d20681c-8c60-448a-b326-a995ae8474ed
		summarizeBy: none
		sourceColumn: Event ID

		annotation SummarizationSetBy = Automatic

	column 'Event date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f48dfa19-7432-4e99-8714-e83814cabd15
		summarizeBy: none
		sourceColumn: Event date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Expiry date'
		dataType: string
		lineageTag: 7314c8b5-d97d-48ed-80b3-b5199f583a3d
		summarizeBy: none
		sourceColumn: Expiry date

		annotation SummarizationSetBy = Automatic

	column 'Event type'
		dataType: string
		lineageTag: 0fccb9d8-f38e-43bd-8e35-95b38d22f87d
		summarizeBy: none
		sourceColumn: Event type

		annotation SummarizationSetBy = Automatic

	column 'Event value'
		dataType: string
		lineageTag: 1bcda137-584e-4b8b-a4fc-b40718096542
		summarizeBy: none
		sourceColumn: Event value

		annotation SummarizationSetBy = Automatic

	column Notes
		dataType: string
		lineageTag: aee43e5e-1fe5-4195-b214-e69185b0ecfe
		summarizeBy: none
		sourceColumn: Notes

		annotation SummarizationSetBy = Automatic

	column Project
		dataType: string
		lineageTag: fd2bd845-d347-4921-b350-a120a2497c57
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column Activity
		dataType: string
		lineageTag: 4ce357d9-e4b2-4344-8c0c-9745436f7d89
		summarizeBy: none
		sourceColumn: Activity

		annotation SummarizationSetBy = Automatic

	column 'Activity Group'
		dataType: string
		lineageTag: 28c7b8aa-80a5-4ebe-b08c-1e8efae14b01
		summarizeBy: none
		sourceColumn: Activity Group

		annotation SummarizationSetBy = Automatic

	column 'Activity Type'
		dataType: string
		lineageTag: 903bc2ab-5205-410f-8f64-371a1dd0cdb9
		summarizeBy: none
		sourceColumn: Activity Type

		annotation SummarizationSetBy = Automatic

	column 'Recording user first name'
		dataType: string
		lineageTag: fdbc94a3-edb4-432a-86ab-8ebc550f96b1
		summarizeBy: none
		sourceColumn: Recording user first name

		annotation SummarizationSetBy = Automatic

	column 'Recording user last name'
		dataType: string
		lineageTag: 252d0404-3d0d-4b61-9b47-6474ffdc0b9f
		summarizeBy: none
		sourceColumn: Recording user last name

		annotation SummarizationSetBy = Automatic

	column 'Date recorded'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6a5fde08-f35d-49b0-8d48-909aea5c7db3
		summarizeBy: none
		sourceColumn: Date recorded

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Time recorded'
		dataType: dateTime
		formatString: Long Time
		lineageTag: a6d41574-2a9c-4a07-9628-96542a1d8f13
		summarizeBy: none
		sourceColumn: Time recorded

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition InfraTLE = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://cyacumbria.sharepoint.com/sites/CYAAllStaff/Shared%20Documents/General/Data%20Team/Staff%20Cards/CYA%20Staff%20Card%20POW%20BI%20V2.xlsx"), null, true),
				    InfraTLE_Table = Source{[Item="InfraTLE",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(InfraTLE_Table,{{"Upshot ID", type text}, {"First name", type text}, {"Last name", type text}, {"Status", type text}, {"Event ID", type text}, {"Event date", type date}, {"Expiry date", type text}, {"Event type", type text}, {"Event value", type text}, {"Notes", type text}, {"Project", type text}, {"Activity", type text}, {"Activity Group", type text}, {"Activity Type", type text}, {"Recording user first name", type text}, {"Recording user last name", type text}, {"Date recorded", type date}, {"Time recorded", type time}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

