table StaffSchedule
	lineageTag: 5ee7cc39-5c40-4193-b141-f5d8855a5c01

	measure TotalScheduledHours =
			
			SUM(StaffSchedule[DailyHours])
		lineageTag: c8bb220e-c3a0-404b-8b44-8499dc19a0a9

	measure 'Total Daily Hours' = SUM('StaffSchedule'[DailyHours])
		lineageTag: ea0de2d9-a3f5-48c9-879d-581e48019f59

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column StaffID
		lineageTag: b278679b-4a9d-42b5-a26e-0dff10113e51
		summarizeBy: none
		isNameInferred
		sourceColumn: Staff ID[StaffID]

		annotation SummarizationSetBy = Automatic

	column 'Staff Name'
		lineageTag: a4fbd6d4-9101-4b0f-85e6-40389e915c75
		summarizeBy: none
		isNameInferred
		sourceColumn: Staff ID[Staff Name]

		annotation SummarizationSetBy = Automatic

	column ContractType
		lineageTag: 335aaaaa-4aa6-4eba-a730-b8fc047af070
		summarizeBy: none
		isNameInferred
		sourceColumn: Staff ID[ContractType]

		annotation SummarizationSetBy = Automatic

	column Date
		formatString: Long Date
		lineageTag: ed33537d-5e9a-46b3-90dd-fb7770821189
		summarizeBy: none
		isNameInferred
		sourceColumn: DateTable[Date]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Year
		formatString: 0
		lineageTag: ad16d92d-5475-4d60-918d-5dc9eb507e80
		summarizeBy: sum
		isNameInferred
		sourceColumn: DateTable[Year]

		annotation SummarizationSetBy = Automatic

	column Month
		lineageTag: 37120cb7-dab7-4051-b908-dd4c877422d0
		summarizeBy: none
		isNameInferred
		sourceColumn: DateTable[Month]

		annotation SummarizationSetBy = Automatic

	column MonthNumber
		formatString: 0
		lineageTag: c83284f4-152c-47c3-9397-530b705144ce
		summarizeBy: sum
		isNameInferred
		sourceColumn: DateTable[MonthNumber]

		annotation SummarizationSetBy = Automatic

	column DayName
		lineageTag: 6adaf17c-8764-45a6-bf76-1998cfed9de9
		summarizeBy: none
		isNameInferred
		sourceColumn: DateTable[DayName]

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		formatString: 0
		lineageTag: aa70a9d6-7b86-4ee1-8111-bf86f53125ba
		summarizeBy: sum
		isNameInferred
		sourceColumn: DateTable[DayOfWeek]

		annotation SummarizationSetBy = Automatic

	column IsHoliday
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 46823411-e4b0-4bf5-b920-2e73fa50a605
		summarizeBy: none
		isNameInferred
		sourceColumn: DateTable[IsHoliday]

		annotation SummarizationSetBy = Automatic

	column PartTimeHours
		lineageTag: 7439e245-14bc-4c6e-8276-83df635f0714
		summarizeBy: sum
		isNameInferred
		sourceColumn: DateTable[PartTimeHours]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FullTimeHours
		lineageTag: 3e7f21bb-2d5c-4cb9-b369-e6b5ca6a120c
		summarizeBy: sum
		isNameInferred
		sourceColumn: DateTable[FullTimeHours]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Test = ```
			[ContractType] & " - " & [DayName] & " - " & IF([IsHoliday], "Holiday", "Workday")
			
			```
		lineageTag: 8e9c9dd3-ae70-4860-bc0e-882f8aded16a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DailyHours = ```
			
			VAR Contract = RELATED ( 'Staff ID'[ContractType] )
			VAR Day      = [DayName]
			VAR Holiday  = [IsHoliday]
			VAR Hours =
			    IF (
			        Holiday,
			        0,
			        SWITCH (
			            TRUE(),
			            Contract = "Full Time" && Day IN {"Saturday","Sunday"}, 0,
			            Contract = "Full Time" && Day = "Friday", 7,
			            Contract = "Full Time", 7.5,
			
			            Contract = "PT1" && Day IN {"Monday","Saturday","Sunday"}, 0,
			            Contract = "PT1" && Day = "Friday", 7,
			            Contract = "PT1" && Day IN {"Tuesday","Wednesday","Thursday"}, 7.5,
			
			            Contract = "PT2" && Day IN {"Friday","Saturday","Sunday"}, 0,
			            Contract = "PT2" && Day = "Monday", 4,
			            Contract = "PT2" && Day IN {"Tuesday","Wednesday","Thursday"}, 7.5,
			
			            Contract = "PT3" && Day IN {"Friday","Saturday","Sunday"}, 0,
			            Contract = "PT3" && Day IN {"Monday","Tuesday","Wednesday","Thursday"}, 7.5,
			
			            0
			        )
			    )
			RETURN COALESCE ( Hours, 0 )
			
			```
		formatString: 0.00
		lineageTag: 3d89c6fc-51bd-40f6-9435-2f9364f3f3a5
		summarizeBy: none

		annotation SummarizationSetBy = User

	column Project
		lineageTag: fb5f6fd1-cc92-49bd-ac21-d1b7c545b991
		summarizeBy: none
		isNameInferred
		sourceColumn: Staff ID[Project]

		annotation SummarizationSetBy = Automatic

	column 'Project Code'
		lineageTag: b9c4092d-0434-4fde-9838-7336d8af04ed
		summarizeBy: none
		isNameInferred
		sourceColumn: Staff ID[Project Code]

		annotation SummarizationSetBy = Automatic

	column 'Upshot ID'
		lineageTag: 29153190-6e11-4c1d-8ed6-a8da33eb6c12
		summarizeBy: none
		isNameInferred
		sourceColumn: Staff ID[Upshot ID]

		annotation SummarizationSetBy = Automatic

	column _NameN
		lineageTag: 7f3124a3-a21f-449c-9267-6680b1616352
		summarizeBy: none
		isNameInferred
		sourceColumn: Staff ID[_NameN]

		annotation SummarizationSetBy = Automatic

	column HoursContracted
		lineageTag: 84311637-e6cc-442f-8acc-9b040e99b0be
		summarizeBy: none
		isNameInferred
		sourceColumn: Staff ID[HoursContracted]

		annotation SummarizationSetBy = Automatic

	partition StaffSchedule = calculated
		mode: import
		source = ```
				
				CROSSJOIN(
				    'Staff ID',
				    FILTER(
				        DateTable,
				        DateTable[DayOfWeek]
				    )
				)
				
				
				```

	annotation PBI_Id = af3d0e47873348a3b89ac01a3fdd0237

