table 'Young People'
	lineageTag: c83bb040-e763-447c-b6ce-b58a4fa1c041

	column 'Upshot ID'
		dataType: string
		lineageTag: 448ec1e8-f060-49e2-b826-9c2f797c7a69
		summarizeBy: none
		sourceColumn: Upshot ID

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 5044914e-5eb5-4fe5-bfc8-112843f6e833
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Archived on'
		dataType: dateTime
		formatString: Long Date
		lineageTag: cada0d04-c30d-4f18-9935-18bf2f695d99
		summarizeBy: none
		sourceColumn: Archived on

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'First Name'
		dataType: string
		lineageTag: 51d42c33-f0ba-4054-84ae-d9d695a0fa60
		summarizeBy: none
		sourceColumn: First Name

		annotation SummarizationSetBy = Automatic

	column 'Last Name'
		dataType: string
		lineageTag: cbb372ff-4b3b-4e4c-b4d9-8d739b5bfc77
		summarizeBy: none
		sourceColumn: Last Name

		annotation SummarizationSetBy = Automatic

	column Nickname
		dataType: string
		lineageTag: dc72d807-7055-44b8-b7a2-09a7445299b2
		summarizeBy: none
		sourceColumn: Nickname

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 7211d729-1669-4afa-bb80-ee71597cd6bc
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column 'Date of Birth'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e487faaf-ab7e-47cf-921f-6c5154224565
		summarizeBy: none
		sourceColumn: Date of Birth

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Age
		dataType: int64
		formatString: 0
		lineageTag: f8f20f5b-df3a-4262-8ef6-0ddae60ab2a7
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column 'Identifying notes'
		dataType: string
		lineageTag: 96a1a4db-513f-4501-bc5a-7998a027c3ec
		summarizeBy: none
		sourceColumn: Identifying notes

		annotation SummarizationSetBy = Automatic

	column 'Address line 1'
		dataType: string
		lineageTag: 6b3a1e6c-ff6e-4b4e-842d-8f83f2cbdaac
		summarizeBy: none
		sourceColumn: Address line 1

		annotation SummarizationSetBy = Automatic

	column 'Address line 2'
		dataType: string
		lineageTag: fc066a13-61d1-41b5-a8b7-f4054dc146be
		summarizeBy: none
		sourceColumn: Address line 2

		annotation SummarizationSetBy = Automatic

	column 'Address line 3'
		dataType: string
		lineageTag: 176f1de0-1cff-4f01-b22f-3ad20c422579
		summarizeBy: none
		sourceColumn: Address line 3

		annotation SummarizationSetBy = Automatic

	column Town/City
		dataType: string
		lineageTag: 4ee9633e-0137-4d4a-a00d-26f84b5c29c9
		summarizeBy: none
		sourceColumn: Town/City

		annotation SummarizationSetBy = Automatic

	column County
		dataType: string
		lineageTag: f48e4111-5903-4b52-987e-f4a63bc35d63
		summarizeBy: none
		sourceColumn: County

		annotation SummarizationSetBy = Automatic

	column Postcode
		dataType: string
		lineageTag: 55414d36-9026-4c7c-a161-7d6ee6e8b521
		summarizeBy: none
		sourceColumn: Postcode

		annotation SummarizationSetBy = Automatic

	column Longitude
		dataType: double
		lineageTag: bdf7097c-6cd2-4a71-aac9-faa1504870e0
		summarizeBy: sum
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Latitude
		dataType: double
		lineageTag: 226650e9-f6af-4fe4-9878-877f79e705e8
		summarizeBy: sum
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Strategic Authority'
		dataType: string
		lineageTag: 759ddc72-8f8c-432c-9afe-889ac103145e
		summarizeBy: none
		sourceColumn: Strategic Authority

		annotation SummarizationSetBy = Automatic

	column 'County or Unitary Authority'
		dataType: string
		lineageTag: 87cab950-f923-4958-9f2a-ce00c9174029
		summarizeBy: none
		sourceColumn: County or Unitary Authority

		annotation SummarizationSetBy = Automatic

	column 'Local Authority'
		dataType: string
		lineageTag: 68cc597b-f924-4237-9044-0f604879ef94
		summarizeBy: none
		sourceColumn: Local Authority

		annotation SummarizationSetBy = Automatic

	column Constituency
		dataType: string
		lineageTag: c5e66eea-2712-4640-9d40-76425c7ea324
		summarizeBy: none
		sourceColumn: Constituency

		annotation SummarizationSetBy = Automatic

	column Ward
		dataType: string
		lineageTag: 22687a16-f945-4f96-a333-151a6cea6f59
		summarizeBy: none
		sourceColumn: Ward

		annotation SummarizationSetBy = Automatic

	column 'LSOA code'
		dataType: string
		lineageTag: 8fe45fda-5541-4b21-8151-6507184db1d2
		summarizeBy: none
		sourceColumn: LSOA code

		annotation SummarizationSetBy = Automatic

	column 'IMD percent'
		dataType: int64
		formatString: 0
		lineageTag: ca432d69-ffa6-4c12-9985-569ac4ce896b
		summarizeBy: sum
		sourceColumn: IMD percent

		annotation SummarizationSetBy = Automatic

	column 'Contact relationship type'
		dataType: string
		lineageTag: d4978441-05c1-4979-b09c-82c857c087ed
		summarizeBy: none
		sourceColumn: Contact relationship type

		annotation SummarizationSetBy = Automatic

	column 'Contact first name'
		dataType: string
		lineageTag: 438e5d74-7fdd-4a21-85e4-c83bc443caf6
		summarizeBy: none
		sourceColumn: Contact first name

		annotation SummarizationSetBy = Automatic

	column 'Contact last name'
		dataType: string
		lineageTag: 5375ff56-6eec-4b96-891a-f07b6b77ce91
		summarizeBy: none
		sourceColumn: Contact last name

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: e7565f00-5d57-4655-b7b6-a58e2cfbf18d
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column 'Mobile Phone'
		dataType: string
		lineageTag: 13c60440-f55d-4f8c-8baf-0b38ee3609b7
		summarizeBy: none
		sourceColumn: Mobile Phone

		annotation SummarizationSetBy = Automatic

	column 'Other telephone'
		dataType: string
		lineageTag: a3a8be8b-ba9c-4c87-9ef1-ace7916fc8dc
		summarizeBy: none
		sourceColumn: Other telephone

		annotation SummarizationSetBy = Automatic

	column 'Emergency contact details'
		dataType: string
		lineageTag: 0edb7adc-8f80-4365-ad72-a0f26bd9e4f7
		summarizeBy: none
		sourceColumn: Emergency contact details

		annotation SummarizationSetBy = Automatic

	column 'Specific medical conditions'
		dataType: string
		lineageTag: 87f144d7-3a3c-46a8-9b1d-b6e838673dd3
		summarizeBy: none
		sourceColumn: Specific medical conditions

		annotation SummarizationSetBy = Automatic

	column 'Any other conditions, allergies or dietary requirements etc'
		dataType: string
		lineageTag: 58a5a246-010d-48e8-a8da-148623e22835
		summarizeBy: none
		sourceColumn: Any other conditions, allergies or dietary requirements etc

		annotation SummarizationSetBy = Automatic

	column Disability
		dataType: string
		lineageTag: ac32051c-cb71-4810-8a87-1e9a6767b5f0
		summarizeBy: none
		sourceColumn: Disability

		annotation SummarizationSetBy = Automatic

	column Ethnicity
		dataType: string
		lineageTag: 0cb3acd8-07b4-47cd-a0ce-c5fb22ef41d8
		summarizeBy: none
		sourceColumn: Ethnicity

		annotation SummarizationSetBy = Automatic

	column Faith
		dataType: string
		lineageTag: 5ef2bd3a-a184-482e-8fb4-575435b239e9
		summarizeBy: none
		sourceColumn: Faith

		annotation SummarizationSetBy = Automatic

	column 'Sexual orientation'
		dataType: string
		lineageTag: 8895963d-2f61-4523-820c-dd2c856fe822
		summarizeBy: none
		sourceColumn: Sexual orientation

		annotation SummarizationSetBy = Automatic

	column School/College/University
		dataType: string
		lineageTag: 9af617ef-22e4-455f-8c16-df1a0e753a5b
		summarizeBy: none
		sourceColumn: School/College/University

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 103552b4-89a3-4438-aabc-373bfd483bb8
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column 'Edubase URN'
		dataType: string
		lineageTag: b769a250-a23d-488c-8e56-5dbe3b2696eb
		summarizeBy: none
		sourceColumn: Edubase URN

		annotation SummarizationSetBy = Automatic

	column 'FA number'
		dataType: string
		lineageTag: 51dc363e-8c69-4865-a7eb-7afbd8ee0e11
		summarizeBy: none
		sourceColumn: FA number

		annotation SummarizationSetBy = Automatic

	column 'Membership ID/number'
		dataType: string
		lineageTag: e5bff58f-d3c4-445d-8f31-02d1ff52fd9f
		summarizeBy: none
		sourceColumn: Membership ID/number

		annotation SummarizationSetBy = Automatic

	column 'Has permission: Media consent'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e351cba4-637a-47f7-a5d3-62979f7be4f0
		summarizeBy: none
		sourceColumn: Has permission: Media consent

		annotation SummarizationSetBy = Automatic

	column 'Has permission: Receive surveys via Upshot'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 785ce4ab-3b73-4c07-94ff-651a631f69b4
		summarizeBy: none
		sourceColumn: Has permission: Receive surveys via Upshot

		annotation SummarizationSetBy = Automatic

	column 'Has permission: Receive emails via Upshot'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ae2ccfe8-5f16-4834-82e1-dc2927009921
		summarizeBy: none
		sourceColumn: Has permission: Receive emails via Upshot

		annotation SummarizationSetBy = Automatic

	column Registered
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7846814e-6ae0-4d9e-aefc-861d0199b8e8
		summarizeBy: none
		sourceColumn: Registered

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Added to Upshot'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9ec45945-a0aa-4872-bf3e-235f98352ca0
		summarizeBy: none
		sourceColumn: Added to Upshot

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Added by'
		dataType: string
		lineageTag: 3346fbb0-64b1-4a7b-9ea5-71930ccbbf0a
		summarizeBy: none
		sourceColumn: Added by

		annotation SummarizationSetBy = Automatic

	column 'Added via'
		dataType: string
		lineageTag: e277de1d-c689-4457-8ccd-512b7866f2d7
		summarizeBy: none
		sourceColumn: Added via

		annotation SummarizationSetBy = Automatic

	column 'Last updated'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f2e236f3-02b5-4487-aeec-54fbee101b97
		summarizeBy: none
		sourceColumn: Last updated

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Last updated by'
		dataType: string
		lineageTag: a5182afc-fcd6-4b85-91e8-ed35e072eb3e
		summarizeBy: none
		sourceColumn: Last updated by

		annotation SummarizationSetBy = Automatic

	column 'First session in time period'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 27899ab9-870e-4149-aff4-b5667391282c
		summarizeBy: none
		sourceColumn: First session in time period

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Last session in time period'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 291216c1-0246-4904-8b95-2d7ae1424c69
		summarizeBy: none
		sourceColumn: Last session in time period

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Project restrictions'
		dataType: string
		lineageTag: e674e984-a8b3-47f6-b18a-fc6f8fc3a918
		summarizeBy: none
		sourceColumn: Project restrictions

		annotation SummarizationSetBy = Automatic

	column 'NI Number:'
		dataType: string
		lineageTag: 290b28e1-6b63-46b9-bc64-38483afad81d
		summarizeBy: none
		sourceColumn: NI Number:

		annotation SummarizationSetBy = Automatic

	column 'What is the highest level of education you have completed?'
		dataType: string
		lineageTag: e9fa77b7-aa03-43e6-ac4b-216479931892
		summarizeBy: none
		sourceColumn: What is the highest level of education you have completed?

		annotation SummarizationSetBy = Automatic

	column 'Do you have any paid work/long term volunteering experience since leaving school?'
		dataType: string
		lineageTag: 3bb2ab86-ae52-4d73-8b00-c1358d7af81b
		summarizeBy: none
		sourceColumn: Do you have any paid work/long term volunteering experience since leaving school?

		annotation SummarizationSetBy = Automatic

	column 'Do you have a driving licence?'
		dataType: string
		lineageTag: 446f66ae-46a3-4c8f-8dcb-d21a804e9ece
		summarizeBy: none
		sourceColumn: Do you have a driving licence?

		annotation SummarizationSetBy = Automatic

	column 'Status at start of program'
		dataType: string
		lineageTag: 4a1c7110-487f-4b4f-88fc-43a0c40f46c8
		summarizeBy: none
		sourceColumn: Status at start of program

		annotation SummarizationSetBy = Automatic

	column 'How long have you been unemployed?'
		dataType: string
		lineageTag: 009c4396-e587-4a14-88f2-690c49ceab05
		summarizeBy: none
		sourceColumn: How long have you been unemployed?

		annotation SummarizationSetBy = Automatic

	column 'What area/sector would you like to like to work in?'
		dataType: string
		lineageTag: a574158c-40d8-4e84-89fa-50e2c0cfea35
		summarizeBy: none
		sourceColumn: What area/sector would you like to like to work in?

		annotation SummarizationSetBy = Automatic

	column Allergies
		dataType: string
		lineageTag: 6551d781-a9c5-482e-8655-7954889968dd
		summarizeBy: none
		sourceColumn: Allergies

		annotation SummarizationSetBy = Automatic

	column Other
		dataType: string
		lineageTag: 8a0d4f15-03ff-4632-9ecb-6f35cbc5c36e
		summarizeBy: none
		sourceColumn: Other

		annotation SummarizationSetBy = Automatic

	column 'Do you personally consider yourself to have a disability, regardless of clinical diagnosis?'
		dataType: string
		lineageTag: 13a6bf6f-5f2d-4b29-a5b5-8c89afeb201a
		summarizeBy: none
		sourceColumn: Do you personally consider yourself to have a disability, regardless of clinical diagnosis?

		annotation SummarizationSetBy = Automatic

	column 'Do you personally consider yourself to be transgender?'
		dataType: string
		lineageTag: bc0c6eb2-aeb3-4d7b-b947-5ecd6d1b7ac5
		summarizeBy: none
		sourceColumn: Do you personally consider yourself to be transgender?

		annotation SummarizationSetBy = Automatic

	column 'Please indicate if you have any of the following neurodivergent conditions (select all that apply):'
		dataType: string
		lineageTag: 52055a6d-88b1-4ecf-aaf3-e8ed66fe5336
		summarizeBy: none
		sourceColumn: Please indicate if you have any of the following neurodivergent conditions (select all that apply):

		annotation SummarizationSetBy = Automatic

	column 'Do you have access to the following types of healthcare services?'
		dataType: string
		lineageTag: b55c7086-ed53-489f-90cd-fa9ae45ce6e3
		summarizeBy: none
		sourceColumn: Do you have access to the following types of healthcare services?

		annotation SummarizationSetBy = Automatic

	column 'Are you care experienced?'
		dataType: string
		lineageTag: 4c89d6a9-8309-4aaa-8d69-7f55ba9f281d
		summarizeBy: none
		sourceColumn: Are you care experienced?

		annotation SummarizationSetBy = Automatic

	column 'Where is your PA based?'
		dataType: string
		lineageTag: 94fc99bd-8965-4082-a5e5-0766a394a597
		summarizeBy: none
		sourceColumn: Where is your PA based?

		annotation SummarizationSetBy = Automatic

	column Barriers
		dataType: string
		lineageTag: e7aa4dd9-7830-496b-a390-73f247e18378
		summarizeBy: none
		sourceColumn: Barriers

		annotation SummarizationSetBy = Automatic

	column 'If any of the options on ''Barriers to Employment'' said please state, list detail here:'
		dataType: string
		lineageTag: 06e0cea7-8ef3-46f8-9380-7845009ba2c8
		summarizeBy: none
		sourceColumn: If any of the options on 'Barriers to Employment' said please state, list detail here:

		annotation SummarizationSetBy = Automatic

	column Benefits:
		dataType: string
		lineageTag: f3ff039f-9165-4394-ad48-401247405c2a
		summarizeBy: none
		sourceColumn: Benefits:

		annotation SummarizationSetBy = Automatic

	column 'Date of Claim for above:'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c4e8ff2f-67c7-43a9-8c5e-037d5a0225d2
		summarizeBy: none
		sourceColumn: Date of Claim for above:

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Other benefits:'
		dataType: string
		lineageTag: 27eaac3b-1421-48d5-b8af-1f5fa2e7f28d
		summarizeBy: none
		sourceColumn: Other benefits:

		annotation SummarizationSetBy = Automatic

	column 'Living Arrangements:'
		dataType: string
		lineageTag: e2c5b089-c80d-4139-82f3-a4070d20ee32
		summarizeBy: none
		sourceColumn: Living Arrangements:

		annotation SummarizationSetBy = Automatic

	column 'Are you working with any other service?'
		dataType: string
		lineageTag: 3406952a-d94c-4253-bea7-4cc6ae4e3f5d
		summarizeBy: none
		sourceColumn: Are you working with any other service?

		annotation SummarizationSetBy = Automatic

	column 'If other services worked with, please state:'
		dataType: string
		lineageTag: 88ce0428-60d1-48fa-8432-8cf68be6eb34
		summarizeBy: none
		sourceColumn: If other services worked with, please state:

		annotation SummarizationSetBy = Automatic

	column 'Which Services?'
		dataType: string
		lineageTag: ed48741a-0ffa-421c-a740-34d67202b89d
		summarizeBy: none
		sourceColumn: Which Services?

		annotation SummarizationSetBy = Automatic

	column 'Referred from:'
		dataType: string
		lineageTag: 4af10d3b-dd8d-4e95-9a04-e3846976fceb
		summarizeBy: none
		sourceColumn: Referred from:

		annotation SummarizationSetBy = Automatic

	column 'Job Center referred by?'
		dataType: string
		lineageTag: 84bd5a5b-84bd-4695-9d6c-82e44e1ca560
		summarizeBy: none
		sourceColumn: Job Center referred by?

		annotation SummarizationSetBy = Automatic

	column Notes:
		dataType: string
		lineageTag: 5fb30624-93a5-4f2e-b2d1-9363cfea6fb0
		summarizeBy: none
		sourceColumn: Notes:

		annotation SummarizationSetBy = Automatic

	column 'Project(s) involved in:'
		dataType: string
		lineageTag: 9db18476-eb4a-4588-aff5-d287676794e5
		summarizeBy: none
		sourceColumn: Project(s) involved in:

		annotation SummarizationSetBy = Automatic

	column 'Benny Walker Worker'
		dataType: string
		lineageTag: 965b40a4-faf9-4f06-9620-221ce21a7d3d
		summarizeBy: none
		sourceColumn: Benny Walker Worker

		annotation SummarizationSetBy = Automatic

	column 'Forging Futures Worker'
		dataType: string
		lineageTag: b1d1c317-da7f-47d9-b9ab-15bc6fe1d1a9
		summarizeBy: none
		sourceColumn: Forging Futures Worker

		annotation SummarizationSetBy = Automatic

	column 'Maintaining Relationships Worker'
		dataType: string
		lineageTag: 08dd68aa-9d6a-4527-a2a1-078045ad1e73
		summarizeBy: none
		sourceColumn: Maintaining Relationships Worker

		annotation SummarizationSetBy = Automatic

	column 'Leaving Care Worker'
		dataType: string
		lineageTag: 55830358-e172-496e-bc1d-f363ef4721ad
		summarizeBy: none
		sourceColumn: Leaving Care Worker

		annotation SummarizationSetBy = Automatic

	column 'Referral Status'
		dataType: string
		lineageTag: 9064ba65-daa4-4ad6-869d-f68ae212bc10
		summarizeBy: none
		sourceColumn: Referral Status

		annotation SummarizationSetBy = Automatic

	column 'Signposted to:'
		dataType: string
		lineageTag: d3e552bc-e480-4ce5-9456-e4b6da96b414
		summarizeBy: none
		sourceColumn: Signposted to:

		annotation SummarizationSetBy = Automatic

	column 'Type of Profile:'
		dataType: string
		lineageTag: 23addee5-000e-4454-a238-e49032cf697a
		summarizeBy: none
		sourceColumn: Type of Profile:

		annotation SummarizationSetBy = Automatic

	column 'Inspira Worker'
		dataType: string
		lineageTag: 6db6c74a-6491-49bf-ba3f-6be7a361d9f8
		summarizeBy: none
		sourceColumn: Inspira Worker

		annotation SummarizationSetBy = Automatic

	column Sector:
		dataType: string
		lineageTag: 22742ca4-5a11-4fa0-9323-8e106306004a
		summarizeBy: none
		sourceColumn: Sector:

		annotation SummarizationSetBy = Automatic

	column 'What does your organisation offer?'
		dataType: string
		lineageTag: 1d88573a-6411-4652-a495-af57f9a32bd6
		summarizeBy: none
		sourceColumn: What does your organisation offer?

		annotation SummarizationSetBy = Automatic

	column Area(s):
		dataType: string
		lineageTag: baa75005-9a4f-4f48-ad69-dc32d855b48b
		summarizeBy: none
		sourceColumn: Area(s):

		annotation SummarizationSetBy = Automatic

	column 'What age groups do you support?'
		dataType: string
		lineageTag: 2dc8cdd8-d69f-459b-b148-412f14c1fa54
		summarizeBy: none
		sourceColumn: What age groups do you support?

		annotation SummarizationSetBy = Automatic

	column 'Organisations Notes'
		dataType: string
		lineageTag: b4189498-6a2c-458c-8564-b0ca73dbdc1e
		summarizeBy: none
		sourceColumn: Organisations Notes

		annotation SummarizationSetBy = Automatic

	column 'Charity/Company Number'
		dataType: string
		lineageTag: 764d1668-6854-43e9-a193-ff414ae8894e
		summarizeBy: none
		sourceColumn: Charity/Company Number

		annotation SummarizationSetBy = Automatic

	column 'What is the total annual income of your organisation?'
		dataType: string
		lineageTag: 67af58bd-9f73-4b62-84c7-87b8813e1dfd
		summarizeBy: none
		sourceColumn: What is the total annual income of your organisation?

		annotation SummarizationSetBy = Automatic

	column 'How long does the support term last?'
		dataType: string
		lineageTag: d4df1eba-495a-4312-8813-91e69cd61224
		summarizeBy: none
		sourceColumn: How long does the support term last?

		annotation SummarizationSetBy = Automatic

	column 'Where did you learn about this organisation?'
		dataType: string
		lineageTag: 953228f0-522c-495c-89cc-d6da71eb0807
		summarizeBy: none
		sourceColumn: Where did you learn about this organisation?

		annotation SummarizationSetBy = Automatic

	column 'Response time'
		dataType: string
		lineageTag: 7685c837-7d97-43a7-a6b3-9b58be5ddefc
		summarizeBy: none
		sourceColumn: Response time

		annotation SummarizationSetBy = Automatic

	partition 'Young People' = m
		mode: import
		source =
				let
				    WorkbookUrl = "https://cyacumbria.sharepoint.com/sites/CYAAllStaff/Shared%20Documents/General/Data%20Team/Staff%20Cards/CYA%20Staff%20Card%20POW%20BI%20V2.xlsx",
				    Source = Excel.Workbook(Web.Contents(WorkbookUrl), null, true),
				    PeopleTypeMap = {
				        {"Upshot ID", type text},
				        {"Status", type text},
				        {"Archived on", type date},
				        {"First Name", type text},
				        {"Last Name", type text},
				        {"Nickname", type text},
				        {"Gender", type text},
				        {"Date of Birth", type date},
				        {"Age", Int64.Type},
				        {"Identifying notes", type text},
				        {"Address line 1", type text},
				        {"Address line 2", type text},
				        {"Address line 3", type text},
				        {"Town/City", type text},
				        {"County", type text},
				        {"Postcode", type text},
				        {"Longitude", type number},
				        {"Latitude", type number},
				        {"Strategic Authority", type text},
				        {"County or Unitary Authority", type text},
				        {"Local Authority", type text},
				        {"Constituency", type text},
				        {"Ward", type text},
				        {"LSOA code", type text},
				        {"IMD percent", Int64.Type},
				        {"Contact relationship type", type text},
				        {"Contact first name", type text},
				        {"Contact last name", type text},
				        {"Email", type text},
				        {"Mobile Phone", type text},
				        {"Other telephone", type text},
				        {"Emergency contact details", type text},
				        {"Specific medical conditions", type text},
				        {"Any other conditions, allergies or dietary requirements etc", type text},
				        {"Disability", type text},
				        {"Ethnicity", type text},
				        {"Faith", type text},
				        {"Sexual orientation", type text},
				        {"School/College/University", type text},
				        {"Type", type text},
				        {"Edubase URN", type text},
				        {"FA number", type text},
				        {"Membership ID/number", type text},
				        {"Has permission: Media consent", type logical},
				        {"Has permission: Receive surveys via Upshot", type logical},
				        {"Has permission: Receive emails via Upshot", type logical},
				        {"Registered", type date},
				        {"Added to Upshot", type date},
				        {"Added by", type text},
				        {"Added via", type text},
				        {"Last updated", type date},
				        {"Last updated by", type text},
				        {"First session in time period", type date},
				        {"Last session in time period", type date},
				        {"Project restrictions", type text},
				        {"NI Number:", type text},
				        {"What is the highest level of education you have completed?", type text},
				        {"Do you have any paid work/long term volunteering experience since leaving school?", type text},
				        {"Do you have a driving licence?", type text},
				        {"Status at start of program", type text},
				        {"How long have you been unemployed?", type text},
				        {"What area/sector would you like to like to work in?", type text},
				        {"Allergies", type text},
				        {"Other", type text},
				        {"Do you personally consider yourself to have a disability, regardless of clinical diagnosis?", type text},
				        {"Do you personally consider yourself to be transgender?", type text},
				        {"Please indicate if you have any of the following neurodivergent conditions (select all that apply):", type text},
				        {"Do you have access to the following types of healthcare services?", type text},
				        {"Are you care experienced?", type text},
				        {"Where is your PA based?", type text},
				        {"Barriers", type text},
				        {"If any of the options on 'Barriers to Employment' said please state, list detail here:", type text},
				        {"Benefits:", type text},
				        {"Date of Claim for above:", type date},
				        {"Other benefits:", type text},
				        {"Living Arrangements:", type text},
				        {"Are you working with any other service?", type text},
				        {"If other services worked with, please state:", type text},
				        {"Which Services?", type text},
				        {"Referred from:", type text},
				        {"Job Center referred by?", type text},
				        {"Notes:", type text},
				        {"Project(s) involved in:", type text},
				        {"Benny Walker Worker", type text},
				        {"Forging Futures Worker", type text},
				        {"Maintaining Relationships Worker", type text},
				        {"Leaving Care Worker", type text},
				        {"Referral Status", type text},
				        {"Signposted to:", type text},
				        {"Inspira Worker", type text},
				        {"Type of Profile:", type text},
				        {"Sector:", type text},
				        {"What does your organisation offer?", type text},
				        {"Area(s):", type text},
				        {"What age groups do you support?", type text},
				        {"Organisations Notes", type text},
				        {"Charity/Company Number", type text},
				        {"What is the total annual income of your organisation?", type text},
				        {"How long does the support term last?", type text},
				        {"Where did you learn about this organisation?", type text},
				        {"Response time", type text}
				    },
				    GetPeopleTable = (item as text) as table =>
				        let
				            Raw = Source{[Item = item, Kind = "Table"]}[Data],
				            ExistingColumns = List.Select(PeopleTypeMap, each List.Contains(Table.ColumnNames(Raw), _{0})),
				            Typed = Table.TransformColumnTypes(Raw, ExistingColumns, "en-GB"),
				            MissingColumns = List.Select(PeopleTypeMap, each not List.Contains(Table.ColumnNames(Typed), _{0})),
				            WithAllColumns =
				                List.Accumulate(
				                    MissingColumns,
				                    Typed,
				                    (state, current) =>
				                        let
				                            columnName = current{0},
				                            columnType = current{1}
				                        in
				                            Table.AddColumn(state, columnName, each null, columnType)
				                )
				        in
				            WithAllColumns,
				    CombinedPeople = Table.Combine({
				        GetPeopleTable("DOPeople"),
				        GetPeopleTable("BFPeople"),
				        GetPeopleTable("InfraPeople")
				    })
				in
				    CombinedPeople

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

